// =============================================
// =========== DATOS DEL JUEGO =================
// =============================================

const CATEGORIES = {
  "Personajes Disney": {
    icon: "🏰",
    color: "#a78bfa",
    words: [
      { word: "Mickey Mouse", hint: "Mascota Disney" },
      { word: "Minnie Mouse", hint: "Novia de Mickey" },
      { word: "Donald Duck", hint: "Pato enojón Disney" },
      { word: "Goofy", hint: "Perro torpe Disney" },
      { word: "Pluto", hint: "Perro de Mickey" },
      { word: "Pato Donald", hint: "Pato enojón Disney" },
      { word: "Chip y Dale", hint: "Ardillas traviesas Disney" },
      { word: "El Pato Lucas", hint: "Pato Looney Tunes" },
      { word: "Bugs Bunny", hint: "Conejo Looney Tunes" },
      { word: "Tweety", hint: "Canario Looney Tunes" },
      { word: "Simba", hint: "Película Rey León" },
      { word: "Mufasa", hint: "Película Rey León" },
      { word: "Nala", hint: "Película Rey León" },
      { word: "Timón", hint: "Suricata Rey León" },
      { word: "Pumba", hint: "Jabalí Rey León" },
      { word: "Scar", hint: "Villano Rey León" },
      { word: "Ariel", hint: "Película La Sirenita" },
      { word: "Úrsula", hint: "Bruja La Sirenita" },
      { word: "Sebastián", hint: "Cangrejo La Sirenita" },
      { word: "Flounder", hint: "Pez La Sirenita" },
      { word: "El Príncipe Eric", hint: "Príncipe La Sirenita" },
      { word: "Blancanieves", hint: "Princesa Disney clásica" },
      { word: "La Madrastra Malvada", hint: "Villana Blancanieves" },
      { word: "Cenicienta", hint: "Princesa Disney clásica" },
      { word: "El Hada Madrina", hint: "Hada Cenicienta" },
      { word: "La Bella Durmiente", hint: "Princesa Disney clásica" },
      { word: "Maléfica", hint: "Bruja Bella Durmiente" },
      { word: "Bella", hint: "Película La Bestia" },
      { word: "La Bestia", hint: "Película Bella y Bestia" },
      { word: "Gastón", hint: "Villano Bella y Bestia" },
      { word: "Lumière", hint: "Candelabro Bella y Bestia" },
      { word: "Ding Dong", hint: "Reloj Bella y Bestia" },
      { word: "Aladdín", hint: "Película Disney Aladdín" },
      { word: "Jasmine", hint: "Princesa de Agrabah" },
      { word: "Jafar", hint: "Villano de Agrabah" },
      { word: "El Genio", hint: "Genio de la lámpara" },
      { word: "Iago", hint: "Loro de Jafar" },
      { word: "Woody", hint: "Vaquero Toy Story" },
      { word: "Buzz Lightyear", hint: "Astronauta Toy Story" },
      { word: "Jessie", hint: "Vaquera Toy Story" },
      { word: "Rex", hint: "Dinosaurio Toy Story" },
      { word: "Hamm", hint: "Chanchito Toy Story" },
      { word: "El Señor Cara de Papa", hint: "Juguete Toy Story" },
      { word: "Elsa", hint: "Película Frozen" },
      { word: "Anna", hint: "Película Frozen" },
      { word: "Olaf", hint: "Muñeco nieve Frozen" },
      { word: "Kristoff", hint: "Joven Frozen" },
      { word: "Hans", hint: "Príncipe Frozen" },
      { word: "Nemo", hint: "Pez payaso Pixar" },
      { word: "Dory", hint: "Pez azul Pixar" },
      { word: "Marlin", hint: "Papá de Nemo" },
      { word: "El Tiburón Bruceico", hint: "Tiburón Buscando a Nemo" },
      { word: "Remy", hint: "Rata cocinera Ratatouille" },
      { word: "WALL-E", hint: "Robot basura Pixar" },
      { word: "Rayo McQueen", hint: "Auto de carreras Cars" },
      { word: "Mater", hint: "Grúa rústica Cars" },
      { word: "Edna Moda", hint: "Diseñadora Los Increíbles" },
      { word: "Mr. Increíble", hint: "Superhéroe Pixar" },
      { word: "Mirabel", hint: "Película Encanto" },
      { word: "Luisa", hint: "Superheroína Encanto" },
      { word: "Isabela", hint: "Hermana flores Encanto" },
      { word: "Bruno", hint: "Película Encanto" },
      { word: "Hércules", hint: "Semidiós película Disney" },
      { word: "Megara", hint: "Heroína Hércules Disney" },
      { word: "Hades", hint: "Villano Hércules Disney" },
      { word: "Mulan", hint: "Guerrera película Disney" },
      { word: "Moana", hint: "Princesa oceánica Disney" },
      { word: "Maui", hint: "Semidiós película Moana" },
      { word: "Tiana", hint: "Princesa Sapo Disney" },
      { word: "Pocahontas", hint: "Princesa nativa Disney" },
      { word: "Stitch", hint: "Alien azul Lilo y Stitch" },
      { word: "Lilo", hint: "Niña hawaiana Disney" },
      { word: "Bambi", hint: "Ciervo clásico Disney" },
      { word: "Dumbo", hint: "Elefante orejón Disney" },
      { word: "Pinocho", hint: "Marioneta clásico Disney" },
      { word: "Jiminy Cricket", hint: "Grillo Pinocho Disney" },
      { word: "Mowgli", hint: "Niño El Libro de la Selva" },
      { word: "Baloo", hint: "Oso El Libro de la Selva" },
      { word: "Shere Khan", hint: "Tigre El Libro de la Selva" },
      { word: "Jack Skellington", hint: "Rey del Espanto Halloween" },
      { word: "Capitán Garfio", hint: "Villano Peter Pan" },
      { word: "Campanita", hint: "Hada Peter Pan" },
      { word: "Mérida", hint: "Princesa Valiente Pixar" },
      { word: "Rapunzel", hint: "Princesa pelos largos Disney" },
      // --- NUEVOS ---
      { word: "Tarzán", hint: "Hombre mono Disney" },
      { word: "Jane Porter", hint: "Exploradora enamorada de Tarzán" },
      { word: "Mushu", hint: "Dragón rojo Mulán" },
      { word: "Cruella de Vil", hint: "Villana 101 Dálmatas" },
      { word: "Mary Poppins", hint: "Niñera mágica con paraguas" },
      { word: "Alicia", hint: "Niña País de las Maravillas" },
      { word: "Sombrerero Loco", hint: "Amigo de Alicia toma té" },
      { word: "Alegría", hint: "Emoción amarilla Intensamente" },
      { word: "Tristeza", hint: "Emoción azul Intensamente" },
      { word: "Furia", hint: "Emoción roja Intensamente" },
      { word: "Miguel", hint: "Niño músico Coco" },
      { word: "Héctor", hint: "Esqueleto amigo Coco" },
      { word: "Baymax", hint: "Robot médico inflable Grandes Héroes" },
      { word: "Ralph el Demoledor", hint: "Villano arcade que quiere ser bueno" },
      { word: "Vanellope", hint: "Niña corredora Sugar Rush" },
      { word: "Mike Wazowski", hint: "Monstruo verde un ojo" },
      { word: "James P. Sullivan", hint: "Monstruo peludo azul y violeta" },
      { word: "Boo", hint: "Niña humana Monsters Inc" }
    ]
  },

  "Superhéroes": {
    icon: "🦸",
    color: "#f59e0b",
    words: [
      { word: "Spider-Man", hint: "Hombre Araña Marvel" },
      { word: "Iron Man", hint: "Tony Stark Marvel" },
      { word: "Capitán América", hint: "Escudo Marvel Avengers" },
      { word: "Thor", hint: "Dios del Trueno Marvel" },
      { word: "Hulk", hint: "Gigante verde Marvel" },
      { word: "Viuda Negra", hint: "Espía Avengers Marvel" },
      { word: "Ojo de Halcón", hint: "Arquero Avengers Marvel" },
      { word: "Ant-Man", hint: "Superhéroe pequeño Marvel" },
      { word: "Doctor Strange", hint: "Hechicero Supremo Marvel" },
      { word: "Pantera Negra", hint: "Rey de Wakanda" },
      { word: "Bruja Escarlata", hint: "Poderes de caos Marvel" },
      { word: "Visión", hint: "Androide Avengers Marvel" },
      { word: "Falcon", hint: "Alas metálicas Marvel" },
      { word: "War Machine", hint: "Armadura de combate Marvel" },
      { word: "Deadpool", hint: "Mercenario cómico Marvel" },
      { word: "Wolverine", hint: "Garras adamantio X-Men" },
      { word: "Star-Lord", hint: "Líder Guardianes Galaxia" },
      { word: "Gamora", hint: "Guerrera Guardianes Galaxia" },
      { word: "Drax", hint: "Destructor Guardianes Galaxia" },
      { word: "Groot", hint: "Árbol Guardianes Galaxia" },
      { word: "Rocket Raccoon", hint: "Mapache Guardianes Galaxia" },
      { word: "Thanos", hint: "Villano Guante del Infinito" },
      { word: "Loki", hint: "Dios del engaño Marvel" },
      { word: "Hela", hint: "Diosa de la Muerte Marvel" },
      { word: "Cíclope", hint: "Rayos ojos X-Men" },
      { word: "Jean Grey", hint: "Telépata X-Men" },
      { word: "Tormenta", hint: "Controla el clima X-Men" },
      { word: "Bestia", hint: "Hombre azul X-Men" },
      { word: "Magneto", hint: "Controla el metal X-Men" },
      { word: "Profesor X", hint: "Líder de los X-Men" },
      { word: "Mística", hint: "Metamorfa X-Men" },
      { word: "Venom", hint: "Simbionte negro Marvel" },
      { word: "El Duende Verde", hint: "Villano Spider-Man" },
      { word: "Doctor Octopus", hint: "Tentáculos Spider-Man" },
      { word: "Electro", hint: "Villano eléctrico Spider-Man" },
      { word: "Ultron", hint: "Robot villano Avengers" },
      { word: "Dormammu", hint: "Villano Doctor Strange" },
      { word: "Red Skull", hint: "Villano Capitán América" },
      { word: "Superman", hint: "Superhéroe Kryptón DC" },
      { word: "Batman", hint: "Murciélago Gotham DC" },
      { word: "Wonder Woman", hint: "Guerrera amazona DC" },
      { word: "Flash", hint: "Superhéroe más rápido DC" },
      { word: "Linterna Verde", hint: "Anillo poder DC" },
      { word: "Aquaman", hint: "Rey de Atlantis DC" },
      { word: "Shazam", hint: "Niño superhéroe DC" },
      { word: "Cyborg", hint: "Mitad hombre mitad máquina DC" },
      { word: "Supergirl", hint: "Prima de Superman DC" },
      { word: "Nightwing", hint: "Ex Robin DC" },
      { word: "El Joker", hint: "Payaso villano Batman" },
      { word: "Lex Luthor", hint: "Villano Superman DC" },
      { word: "Harley Quinn", hint: "Novia del Joker DC" },
      { word: "El Pingüino", hint: "Villano Batman DC" },
      { word: "Catwoman", hint: "Ladrona Batman DC" },
      { word: "Bane", hint: "Villano rompe Batman" },
      { word: "El Acertijo", hint: "Villano acertijos Batman" },
      { word: "Doomsday", hint: "Monstruo mató Superman" },
      { word: "Robin", hint: "Compañero de Batman" },
      { word: "Raven", hint: "Hechicera Teen Titans" },
      { word: "Starfire", hint: "Alienígena Teen Titans" },
      { word: "Kang el Conquistador", hint: "Villano del tiempo Marvel" },
      { word: "Silver Surfer", hint: "Heraldo de Galactus Marvel" },
      { word: "Galactus", hint: "Devorador de planetas Marvel" },
      { word: "Hulka", hint: "Prima verde de Hulk" },
      { word: "Thor Jane Foster", hint: "Jane Foster con martillo" },
      { word: "Captain Marvel", hint: "Superheroína cósmica Marvel" },
      { word: "Nick Furia", hint: "Director de SHIELD Marvel" },
      { word: "Spider-Man Miles Morales", hint: "Spider-Man afrolatino Marvel" },
      // --- NUEVOS ---
      { word: "Daredevil", hint: "Diablo de Hell's Kitchen ciego Marvel" },
      { word: "Punisher", hint: "El Castigador calavera Marvel" },
      { word: "Ghost Rider", hint: "Vengador Fantasma moto llamas" },
      { word: "Mr. Fantástico", hint: "Líder elástico 4 Fantásticos" },
      { word: "La Antorcha Humana", hint: "Fuego 4 Fantásticos" },
      { word: "La Mole", hint: "Gigante de piedra 4 Fantásticos" },
      { word: "La Mujer Invisible", hint: "Campos de fuerza 4 Fantásticos" },
      { word: "Homelander", hint: "Villano Superman The Boys" },
      { word: "Carnicero (Butcher)", hint: "Odia supers The Boys" },
      { word: "Invencible", hint: "Hijo de Omni-Man serie animada" },
      { word: "Omni-Man", hint: "Padre bigotudo Invencible" },
      { word: "Batgirl", hint: "Chica murciélago DC" },
      { word: "Red Hood", hint: "Jason Todd resucitado DC" },
      { word: "Blade", hint: "Cazador de vampiros Marvel" }
    ]
  },

  "Animé": {
    icon: "⛩️",
    color: "#f97316",
    words: [
      { word: "Goku", hint: "Protagonista Dragon Ball" },
      { word: "Vegeta", hint: "Príncipe Saiyan Dragon Ball" },
      { word: "Piccolo", hint: "Namekiano Dragon Ball" },
      { word: "Gohan", hint: "Hijo de Goku Dragon Ball" },
      { word: "Krilin", hint: "Mejor amigo Goku" },
      { word: "Bulma", hint: "Científica Dragon Ball" },
      { word: "Freezer", hint: "Villano Dragon Ball Z" },
      { word: "Cell", hint: "Androide villano Dragon Ball" },
      { word: "Majin Buu", hint: "Villano gordo Dragon Ball" },
      { word: "Trunks", hint: "Hijo de Vegeta Dragon Ball" },
      { word: "Androide 18", hint: "Androide Dragon Ball Z" },
      { word: "Broly", hint: "Saiyan legendario Dragon Ball" },
      { word: "Bardock", hint: "Padre de Goku Dragon Ball" },
      { word: "Naruto", hint: "Ninja con zorro Naruto" },
      { word: "Sasuke", hint: "Rival de Naruto" },
      { word: "Sakura", hint: "Kunoichi del equipo 7" },
      { word: "Kakashi", hint: "Sensei del equipo 7" },
      { word: "Itachi", hint: "Hermano de Sasuke Naruto" },
      { word: "Gaara", hint: "Ninja de la arena Naruto" },
      { word: "Jiraiya", hint: "Maestro sapo Naruto" },
      { word: "Hinata", hint: "Ninja tímida Naruto" },
      { word: "Obito", hint: "Villano enmascarado Naruto" },
      { word: "Luffy", hint: "Capitán pirata One Piece" },
      { word: "Zoro", hint: "Espadachín tres espadas One Piece" },
      { word: "Nami", hint: "Navegante One Piece" },
      { word: "Usopp", hint: "Francotirador One Piece" },
      { word: "Sanji", hint: "Cocinero One Piece" },
      { word: "Chopper", hint: "Reno médico One Piece" },
      { word: "Shanks", hint: "Yonko pelirrojo One Piece" },
      { word: "Barba Blanca", hint: "Yonko One Piece" },
      { word: "Portgas D. Ace", hint: "Hermano de Luffy One Piece" },
      { word: "Doflamingo", hint: "Villano One Piece" },
      { word: "Boa Hancock", hint: "Emperatriz One Piece" },
      { word: "Tanjiro Kamado", hint: "Cazador de demonios Kimetsu" },
      { word: "Nezuko Kamado", hint: "Hermana demonio Kimetsu" },
      { word: "Zenitsu", hint: "Cazador rayo Kimetsu" },
      { word: "Inosuke", hint: "Máscara jabalí Kimetsu" },
      { word: "Giyu Tomioka", hint: "Pilar del agua Kimetsu" },
      { word: "Muzan Kibutsuji", hint: "Rey demonio Kimetsu" },
      { word: "Deku", hint: "Héroe protagonista My Hero" },
      { word: "Bakugo", hint: "Explosiones My Hero Academia" },
      { word: "Todoroki", hint: "Hielo y fuego My Hero" },
      { word: "All Might", hint: "Símbolo de la paz My Hero" },
      { word: "Uraraka", hint: "Gravedad cero My Hero" },
      { word: "Endeavor", hint: "Flamero My Hero Academia" },
      { word: "Dabi", hint: "Llamas azules My Hero" },
      { word: "Eren Yeager", hint: "Attack on Titan protagonista" },
      { word: "Mikasa Ackerman", hint: "Guerrera Attack on Titan" },
      { word: "Armin Arlert", hint: "Estratega Attack on Titan" },
      { word: "Levi Ackerman", hint: "Capitán Attack on Titan" },
      { word: "Edward Elric", hint: "Alquimista de metal Fullmetal" },
      { word: "Alphonse Elric", hint: "Armadura Fullmetal Alchemist" },
      { word: "Roy Mustang", hint: "Alquimista del fuego Fullmetal" },
      { word: "Light Yagami", hint: "Estudiante cuaderno Death Note" },
      { word: "L Lawliet", hint: "Detective excéntrico Death Note" },
      { word: "Ryuk", hint: "Shinigami Death Note" },
      { word: "Misa Amane", hint: "Modelo Death Note" },
      { word: "Ash Ketchum", hint: "Entrenador Pokémon" },
      { word: "Misty", hint: "Entrenadora agua Pokémon" },
      { word: "Brock", hint: "Entrenador roca Pokémon" },
      { word: "El Team Rocket", hint: "Villanos Pokémon" },
      { word: "Jessie y James", hint: "Dúo Team Rocket Pokémon" },
      { word: "Sailor Moon", hint: "Guerrera lunar mágica" },
      { word: "Sailor Mars", hint: "Guerrera del fuego Sailor Moon" },
      { word: "Tuxedo Mask", hint: "Caballero misterioso Sailor Moon" },
      { word: "Androide 17", hint: "Androide Dragon Ball Z" },
      { word: "Vegetto", hint: "Fusión Goku y Vegeta" },
      { word: "Gogeta", hint: "Fusión danza Goku Vegeta" },
      { word: "Kirito", hint: "Espadachín SAO" },
      { word: "Asuna", hint: "Guerrera SAO" },
      { word: "Historia Reiss", hint: "Reina Attack on Titan" },
      { word: "Erwin Smith", hint: "Comandante Attack on Titan" },
      { word: "Oliver Atom", hint: "Fútbol Oliver y Benji" },
      { word: "Benji Price", hint: "Arquero Oliver y Benji" },
      { word: "Mark Lenders", hint: "Rival Oliver y Benji" },
      { word: "Doraemon", hint: "Gato robot del futuro" },
      { word: "Seiya de Pegaso", hint: "Caballero del Zodiaco" },
      { word: "Shiryu del Dragón", hint: "Caballero del Zodiaco" },
      { word: "Hyoga del Cisne", hint: "Caballero del Zodiaco" },
      { word: "Shun de Andrómeda", hint: "Caballero del Zodiaco" },
      { word: "Ikki del Fénix", hint: "Caballero del Zodiaco" },
      // --- NUEVOS ---
      { word: "Saitama", hint: "Calvo que vence de un golpe" },
      { word: "Genos", hint: "Cyborg discípulo One Punch Man" },
      { word: "Gojo Satoru", hint: "Hechicero ojos vendados Jujutsu" },
      { word: "Yuji Itadori", hint: "Recipiente de Sukuna Jujutsu" },
      { word: "Sukuna", hint: "Rey de las maldiciones Jujutsu" },
      { word: "Denji", hint: "Pibe motosierra Chainsaw Man" },
      { word: "Makima", hint: "Jefa misteriosa Chainsaw Man" },
      { word: "Ichigo Kurosaki", hint: "Shinigami espada gigante Bleach" },
      { word: "Jotaro Kujo", hint: "Star Platinum JoJo's" },
      { word: "Dio Brando", hint: "Villano vampiro ZA WARUDO JoJo's" },
      { word: "Gon Freecss", hint: "Niño pescador Hunter x Hunter" },
      { word: "Killua Zoldyck", hint: "Asesino rayo Hunter x Hunter" },
      { word: "Shinji Ikari", hint: "Piloto del EVA-01 Evangelion" },
      { word: "Asuka Langley", hint: "Piloto pelirroja Evangelion" },
      { word: "Rei Ayanami", hint: "Piloto pelo azul Evangelion" },
      { word: "Inuyasha", hint: "Mitad demonio perro espada" },
      { word: "Kagome", hint: "Chica del pozo Inuyasha" }
    ]
  },

  "Videojuegos": {
    icon: "🎮",
    color: "#10b981",
    words: [
      { word: "Mario", hint: "Fontanero Nintendo" },
      { word: "Luigi", hint: "Hermano verde de Mario" },
      { word: "Princesa Peach", hint: "Princesa de Mario Nintendo" },
      { word: "Bowser", hint: "Rey Koopa Mario" },
      { word: "Yoshi", hint: "Dinosaurio verde Mario" },
      { word: "Wario", hint: "Rival gordo de Mario" },
      { word: "Toad", hint: "Hongo amigo Mario" },
      { word: "Donkey Kong", hint: "Gorila Nintendo" },
      { word: "Link", hint: "Héroe de Hyrule Zelda" },
      { word: "Zelda", hint: "Princesa de Hyrule Nintendo" },
      { word: "Ganondorf", hint: "Villano Zelda Nintendo" },
      { word: "Pikachu", hint: "Ratón eléctrico Pokémon" },
      { word: "Charizard", hint: "Dragón fuego Pokémon" },
      { word: "Mewtwo", hint: "Pokémon legendario clon" },
      { word: "Snorlax", hint: "Pokémon dormilón gigante" },
      { word: "Eevee", hint: "Pokémon que evoluciona mucho" },
      { word: "Lucario", hint: "Pokémon de acero y lucha" },
      { word: "Sonic el Erizo", hint: "Erizo veloz SEGA" },
      { word: "Tails", hint: "Zorro dos colas SEGA" },
      { word: "Knuckles", hint: "Equidna rojo SEGA" },
      { word: "Shadow", hint: "Erizo negro SEGA" },
      { word: "Amy Rose", hint: "Erizo rosa enamorada SEGA" },
      { word: "Dr. Eggman", hint: "Villano gordo SEGA" },
      { word: "Kratos", hint: "Dios de la guerra PlayStation" },
      { word: "Atreus", hint: "Hijo de Kratos God of War" },
      { word: "Nathan Drake", hint: "Aventurero Uncharted PlayStation" },
      { word: "Joel", hint: "Sobreviviente The Last of Us" },
      { word: "Ellie", hint: "Joven The Last of Us" },
      { word: "Aloy", hint: "Cazadora Horizon PlayStation" },
      { word: "Lara Croft", hint: "Arqueóloga Tomb Raider" },
      { word: "Crash Bandicoot", hint: "Marsupial loco PlayStation" },
      { word: "Spyro", hint: "Dragón morado PlayStation" },
      { word: "Cloud Strife", hint: "Espadón Final Fantasy VII" },
      { word: "Sephiroth", hint: "Villano Final Fantasy VII" },
      { word: "Tifa Lockhart", hint: "Peleadora Final Fantasy VII" },
      { word: "Aerith", hint: "Florera Final Fantasy VII" },
      { word: "Master Chief", hint: "Spartan Halo Xbox" },
      { word: "Geralt de Rivia", hint: "Brujo The Witcher" },
      { word: "Ciri", hint: "Princesa The Witcher" },
      { word: "Solid Snake", hint: "Espía Metal Gear" },
      { word: "Raiden", hint: "Ciberninjas Metal Gear" },
      { word: "Ezio Auditore", hint: "Asesino Assassin's Creed" },
      { word: "Altaïr", hint: "Asesino Assassin's Creed" },
      { word: "Arthur Morgan", hint: "Vaquero Red Dead Redemption" },
      { word: "John Marston", hint: "Vaquero Red Dead Redemption" },
      { word: "GTA San Andreas - CJ", hint: "Protagonista GTA San Andreas" },
      { word: "GTA V - Trevor", hint: "Loco GTA V" },
      { word: "GTA V - Michael", hint: "Ladrón GTA V" },
      { word: "Mega Man", hint: "Robot azul Capcom" },
      { word: "Pac-Man", hint: "Come puntos arcade" },
      { word: "Messi en FIFA", hint: "10 argentino FIFA" },
      { word: "Mbappé en FIFA", hint: "Delantero francés FIFA" },
      { word: "El Fantasma de Fortnite", hint: "Personaje Battle Royale" },
      { word: "El Impostor de Among Us", hint: "Asesino entre astronautas" },
      { word: "Scorpion", hint: "Ninja fuego Mortal Kombat" },
      { word: "Sub-Zero", hint: "Ninja hielo Mortal Kombat" },
      { word: "Ryu", hint: "Peleador Street Fighter" },
      { word: "Ken", hint: "Rival de Ryu Street Fighter" },
      { word: "Chun-Li", hint: "Peleadora Street Fighter" },
      { word: "Steve de Minecraft", hint: "Constructor mundo pixelado" },
      { word: "Creeper", hint: "Bomba verde Minecraft" },
      { word: "El Personaje de Roblox", hint: "Avatar mundo Roblox" },
      { word: "Samus Aran", hint: "Cazarrecompensas Metroid Nintendo" },
      { word: "Kirby", hint: "Bola rosa Nintendo" },
      { word: "Inkling de Splatoon", hint: "Tirador de tinta Nintendo" },
      { word: "Bowser Jr.", hint: "Hijo de Bowser Mario" },
      { word: "Waluigi", hint: "Rival de Luigi Mario" },
      { word: "Diddy Kong", hint: "Mono amigo Donkey Kong" },
      // --- NUEVOS ---
      { word: "Leon S. Kennedy", hint: "Policía rubio Resident Evil" },
      { word: "Chris Redfield", hint: "Golpea rocas Resident Evil" },
      { word: "Jill Valentine", hint: "Sobreviviente clásica Resident Evil" },
      { word: "Nemesis", hint: "Monstruo STARS Resident Evil" },
      { word: "Gordon Freeman", hint: "Científico palanca Half-Life" },
      { word: "GLaDOS", hint: "IA malvada pastel Portal" },
      { word: "Doomguy", hint: "Mata demonios Doom" },
      { word: "Guile", hint: "Pelo rubio Sonic Boom Street Fighter" },
      { word: "M. Bison", hint: "Villano dictador Street Fighter" },
      { word: "Johnny Cage", hint: "Actor engreído Mortal Kombat" },
      { word: "Squirtle", hint: "Tortuga de agua Pokémon inicial" },
      { word: "Bulbasaur", hint: "Sapo planta Pokémon inicial" },
      { word: "Gengar", hint: "Fantasma morado Pokémon" },
      { word: "Jinx", hint: "Loca pelo azul League of Legends" },
      { word: "Yasuo", hint: "Espadachín viento League of Legends" },
      { word: "Ahri", hint: "Mujer zorro League of Legends" },
      { word: "Marcus Fenix", hint: "Lancer Gears of War Xbox" },
      { word: "Abby", hint: "Golfista polémica The Last of Us 2" }
    ]
  },

  "Famosos Mundiales": {
    icon: "🌍",
    color: "#06b6d4",
    words: [
      { word: "Lionel Messi", hint: "10 argentino fútbol mundial" },
      { word: "Cristiano Ronaldo", hint: "CR7 fútbol Portugal" },
      { word: "Neymar", hint: "Delantero brasileño fútbol" },
      { word: "Kylian Mbappé", hint: "Delantero Francia fútbol" },
      { word: "Erling Haaland", hint: "Goleador noruego fútbol" },
      { word: "Pelé", hint: "Rey del fútbol Brasil" },
      { word: "Ronaldinho", hint: "Brasileño genial fútbol" },
      { word: "Zinedine Zidane", hint: "Francés volante fútbol" },
      { word: "David Beckham", hint: "Inglés modelo fútbol" },
      { word: "Michael Jordan", hint: "Leyenda del básquet NBA" },
      { word: "LeBron James", hint: "Rey del básquet NBA" },
      { word: "Kobe Bryant", hint: "Mamba Negra NBA" },
      { word: "Stephen Curry", hint: "Tirador tres puntos NBA" },
      { word: "Shaquille O'Neal", hint: "Gigante gracioso NBA" },
      { word: "Roger Federer", hint: "Leyenda del tenis suizo" },
      { word: "Rafael Nadal", hint: "Rey del polvo de ladrillo tenis" },
      { word: "Novak Djokovic", hint: "Número uno tenis serbio" },
      { word: "Serena Williams", hint: "Reina del tenis estadounidense" },
      { word: "Usain Bolt", hint: "Hombre más rápido atletismo" },
      { word: "Michael Phelps", hint: "Rey de la natación olímpica" },
      { word: "Muhammad Ali", hint: "Leyenda del boxeo mundial" },
      { word: "Mike Tyson", hint: "Boxeador feroz oreja" },
      { word: "Floyd Mayweather", hint: "Boxeador invicto rico" },
      { word: "Taylor Swift", hint: "Cantante pop estadounidense" },
      { word: "Beyoncé", hint: "Reina del pop R&B" },
      { word: "Rihanna", hint: "Cantante barbadense pop" },
      { word: "Lady Gaga", hint: "Cantante excéntrica pop" },
      { word: "Adele", hint: "Cantante baladas británica" },
      { word: "Bad Bunny", hint: "Rey del reggaetón" },
      { word: "Drake", hint: "Rapero canadiense hip-hop" },
      { word: "Eminem", hint: "Rapero blanco Detroit" },
      { word: "Michael Jackson", hint: "Rey del pop mundial" },
      { word: "Madonna", hint: "Reina del pop" },
      { word: "Elvis Presley", hint: "Rey del rock and roll" },
      { word: "Freddie Mercury", hint: "Vocalista Queen rock" },
      { word: "The Beatles", hint: "Banda legendaria Liverpool" },
      { word: "David Bowie", hint: "Rockero excéntrico británico" },
      { word: "Shakira", hint: "Cantante colombiana pop" },
      { word: "Jennifer Lopez", hint: "JLo cantante actriz" },
      { word: "Justin Bieber", hint: "Cantante canadiense pop joven" },
      { word: "Ariana Grande", hint: "Cantante pop estadounidense" },
      { word: "Leonardo DiCaprio", hint: "Actor Hollywood oscarizado" },
      { word: "Brad Pitt", hint: "Actor famoso Hollywood" },
      { word: "Tom Cruise", hint: "Actor acción Hollywood" },
      { word: "Johnny Depp", hint: "Actor excéntrico Hollywood" },
      { word: "Meryl Streep", hint: "Actriz mejor actriz Hollywood" },
      { word: "Angelina Jolie", hint: "Actriz humanitaria Hollywood" },
      { word: "Scarlett Johansson", hint: "Actriz Viuda Negra Marvel" },
      { word: "Keanu Reeves", hint: "Actor Matrix John Wick" },
      { word: "Ryan Gosling", hint: "Actor canadiense Hollywood" },
      { word: "Elon Musk", hint: "Dueño Tesla SpaceX" },
      { word: "Bill Gates", hint: "Fundador Microsoft" },
      { word: "Mark Zuckerberg", hint: "Fundador Facebook Meta" },
      { word: "Steve Jobs", hint: "Fundador Apple" },
      { word: "Barack Obama", hint: "Expresidente Estados Unidos" },
      { word: "Donald Trump", hint: "Expresidente Estados Unidos" },
      { word: "Selena Gomez", hint: "Cantante actriz Disney" },
      { word: "Oprah Winfrey", hint: "Conductora televisiva famosa" },
      // --- NUEVOS ---
      { word: "Tom Hanks", hint: "Actor Forrest Gump" },
      { word: "Robert De Niro", hint: "Actor mafioso leyenda" },
      { word: "Morgan Freeman", hint: "Actor voz de Dios" },
      { word: "Zendaya", hint: "Actriz Rue Euphoria" },
      { word: "Tom Holland", hint: "Actor actual Spider-Man" },
      { word: "Dua Lipa", hint: "Cantante pop británica levitating" },
      { word: "Rosalía", hint: "Cantante Motomami España" },
      { word: "The Weeknd", hint: "Cantante Blinding Lights" },
      { word: "Billie Eilish", hint: "Cantante pop pelo verde/rubio" },
      { word: "Harry Styles", hint: "Ex One Direction solista" },
      { word: "Paul McCartney", hint: "Beatle bajista zurdo" },
      { word: "Kurt Cobain", hint: "Líder Nirvana grunge" },
      { word: "Pep Guardiola", hint: "DT pelado multicampeón City" },
      { word: "Carlo Ancelotti", hint: "DT ceja levantada Madrid" },
      { word: "Will Smith", hint: "Actor Príncipe del Rap cachetada" }
    ]
  },

  "Famosos Argentinos": {
    icon: "🇦🇷",
    color: "#3b82f6",
    words: [
      { word: "Diego Maradona", hint: "10 ídolo fútbol argentino" },
      { word: "Lionel Messi", hint: "10 argentino fútbol mundial" },
      { word: "Gabriel Batistuta", hint: "Goleador histórico Argentina" },
      { word: "Juan Román Riquelme", hint: "10 Boca fútbol" },
      { word: "Carlos Tevez", hint: "Delantero Boca fútbol" },
      { word: "Sergio Agüero", hint: "Kun delantero fútbol argentino" },
      { word: "Ángel Di María", hint: "Extremo fútbol argentino" },
      { word: "Javier Zanetti", hint: "Capitán Inter fútbol" },
      { word: "Franco Colapinto", hint: "Piloto F1 argentino" },
      { word: "Emanuel Ginóbili", hint: "Básquet NBA San Antonio" },
      { word: "Juan Martín del Potro", hint: "Tenista argentino Grande" },
      { word: "Charly García", hint: "Rockero leyenda argentina" },
      { word: "Gustavo Cerati", hint: "Líder de Soda Stereo" },
      { word: "Fito Páez", hint: "Rockero rosarino argentino" },
      { word: "Luis Alberto Spinetta", hint: "El Flaco rock argentino" },
      { word: "Andrés Calamaro", hint: "Rockero Los Rodríguez Argentina" },
      { word: "La Mona Jiménez", hint: "Cuarteto Córdoba Argentina" },
      { word: "Rodrigo Bueno", hint: "Cuarteto El Potro Argentina" },
      { word: "Los Redondos", hint: "Banda Patricio Rey rock" },
      { word: "Lali Espósito", hint: "Cantante actriz argentina" },
      { word: "Tini Stoessel", hint: "Cantante argentina pop" },
      { word: "Nicki Nicole", hint: "Rapera rosarina argentina" },
      { word: "Duki", hint: "Trap argentino popular" },
      { word: "Bizarrap", hint: "Productor BZRP sesiones" },
      { word: "María Becerra", hint: "Cantante pop argentina" },
      { word: "Trueno", hint: "Rapero joven argentino" },
      { word: "WOS", hint: "Freestyler cantante argentino" },
      { word: "Paulo Londra", hint: "Cantante urbano cordobés" },
      { word: "L-Gante", hint: "Cantante cumbia 420" },
      { word: "Coscu", hint: "Streamer argentino Twitch" },
      { word: "Spreen", hint: "Streamer argentino popular" },
      { word: "Luquitas Rodríguez", hint: "Streamer youtuber argentino" },
      { word: "Martín Cirio (La Faraona)", hint: "Influencer youtuber argentino" },
      { word: "Marcelo Tinelli", hint: "Conductor TV argentino" },
      { word: "Susana Giménez", hint: "Diva conductora televisión argentina" },
      { word: "Mirtha Legrand", hint: "La Chiqui almuerzos TV" },
      { word: "Ricardo Darín", hint: "Actor cine argentino" },
      { word: "Guillermo Francella", hint: "Actor cómico argentino" },
      { word: "Florencia Peña", hint: "Actriz conductora argentina" },
      { word: "Darío Barassi", hint: "Conductor juegos TV argentina" },
      { word: "Santiago del Moro", hint: "Conductor Gran Hermano" },
      { word: "Guido Kaczka", hint: "Conductor juegos TV argentina" },
      { word: "Pampita", hint: "Modelo conductora argentina" },
      { word: "Wanda Nara", hint: "Mediática modelo argentina" },
      { word: "Javier Milei", hint: "Presidente Argentina actual" },
      { word: "Cristina Kirchner", hint: "Expresidenta Argentina" },
      { word: "Mauricio Macri", hint: "Expresidente Argentina" },
      { word: "Sergio Massa", hint: "Político argentino" },
      { word: "Alberto Fernández", hint: "Expresidente Argentina" },
      { word: "Patricia Bullrich", hint: "Política ministra argentina" },
      { word: "Eva Perón", hint: "Evita primera dama histórica" },
      { word: "Juan Domingo Perón", hint: "Expresidente histórico Argentina" },
      { word: "José de San Martín", hint: "Libertador Padre Patria Argentina" },
      { word: "Manuel Belgrano", hint: "Creador bandera argentina" },
      // --- NUEVOS ---
      { word: "Emiliano Dibu Martínez", hint: "Arquero Selección mira que te como" },
      { word: "Lionel Scaloni", hint: "DT creador de la Scaloneta" },
      { word: "Julián Álvarez", hint: "La Araña delantero Selección" },
      { word: "Enzo Fernández", hint: "Volante Chelsea campeón del mundo" },
      { word: "Carlos Bilardo", hint: "DT Narigón campeón 86" },
      { word: "Mercedes Sosa", hint: "La Negra folklore leyenda" },
      { word: "Pappo", hint: "El Carpo guitarrista rock" },
      { word: "Indio Solari", hint: "Cantante Los Redondos pogo" },
      { word: "Emilia Mernes", hint: "Cantante pop brillitos en los ojos" },
      { word: "Tiago PZK", hint: "Cantante Gotti Trap/R&B" },
      { word: "Migue Granados", hint: "Conductor humorista Olga" },
      { word: "Diego Capusotto", hint: "Humorista rock Pomelo/Violencia" },
      { word: "Moria Casán", hint: "La One lengua karateca vedette" },
      { word: "Adrián Suar", hint: "Productor actor Chueco Polka" },
      { word: "Alberto Olmedo", hint: "Capitán Piluso humorista clásico" },
      { word: "Jorge Porcel", hint: "Gordo humorista dupla Olmedo" }
    ]
  },

  "Personajes de TV": {
    icon: "📺",
    color: "#ec4899",
    words: [
      { word: "Walter White", hint: "Químico Breaking Bad" },
      { word: "Jesse Pinkman", hint: "Socio Breaking Bad" },
      { word: "Saul Goodman", hint: "Abogado Breaking Bad" },
      { word: "Mike Ehrmantraut", hint: "Limpiador Breaking Bad" },
      { word: "Jon Snow", hint: "Bastardo Game of Thrones" },
      { word: "Daenerys Targaryen", hint: "Madre de dragones GoT" },
      { word: "Tyrion Lannister", hint: "Enano inteligente GoT" },
      { word: "Cersei Lannister", hint: "Reina villana GoT" },
      { word: "Arya Stark", hint: "Asesina lista GoT" },
      { word: "Sansa Stark", hint: "Señora de Winterfell GoT" },
      { word: "El Rey de la Noche", hint: "Villano zombies GoT" },
      { word: "Rick Grimes", hint: "Sheriff Walking Dead" },
      { word: "Daryl Dixon", hint: "Ballesta Walking Dead" },
      { word: "Negan", hint: "Bate Lucille Walking Dead" },
      { word: "Sheldon Cooper", hint: "Genio molesto Big Bang Theory" },
      { word: "Leonard Hofstadter", hint: "Físico Big Bang Theory" },
      { word: "Penny", hint: "Vecina actriz Big Bang Theory" },
      { word: "Howard Wolowitz", hint: "Ingeniero Big Bang Theory" },
      { word: "Raj Koothrappali", hint: "Astrofísico Big Bang Theory" },
      { word: "Ross Geller", hint: "Paleontólogo Friends" },
      { word: "Rachel Green", hint: "Moda café Friends" },
      { word: "Monica Geller", hint: "Cocinera perfeccionista Friends" },
      { word: "Chandler Bing", hint: "Gracioso sarcástico Friends" },
      { word: "Joey Tribbiani", hint: "Actor comedor Friends" },
      { word: "Phoebe Buffay", hint: "Cantante rara Friends" },
      { word: "Homer Simpson", hint: "Papá torpe Los Simpsons" },
      { word: "Marge Simpson", hint: "Mamá pelo azul Simpsons" },
      { word: "Bart Simpson", hint: "Niño travieso Los Simpsons" },
      { word: "Lisa Simpson", hint: "Niña inteligente Simpsons" },
      { word: "Ned Flanders", hint: "Vecino religioso Simpsons" },
      { word: "El Señor Burns", hint: "Jefe malvado Simpsons" },
      { word: "Cartman", hint: "Gordo malvado South Park" },
      { word: "Kenny McCormick", hint: "Muere siempre South Park" },
      { word: "Stan Marsh", hint: "Protagonista South Park" },
      { word: "Kyle Broflovski", hint: "Judío South Park" },
      { word: "Eleven", hint: "Poderes telecinéticos Stranger Things" },
      { word: "Mike Wheeler", hint: "Protagonista Stranger Things" },
      { word: "Dustin Henderson", hint: "Gracioso Stranger Things" },
      { word: "Lucas Sinclair", hint: "Amigo Stranger Things" },
      { word: "El Demogorgon", hint: "Monstruo Stranger Things" },
      { word: "El Profesor", hint: "Mastermind La Casa de Papel" },
      { word: "Berlín", hint: "Antagonista La Casa de Papel" },
      { word: "Nairobi", hint: "Jefa talleres La Casa de Papel" },
      { word: "Tokio", hint: "Narradora La Casa de Papel" },
      { word: "Denver", hint: "Risa La Casa de Papel" },
      { word: "Pablo Escobar", hint: "Narcotraficante serie Narcos" },
      { word: "Michael Scott", hint: "Jefe ridículo The Office" },
      { word: "Dwight Schrute", hint: "Gerente asistente The Office" },
      { word: "Jim Halpert", hint: "Bromista The Office" },
      { word: "El Mandaloriano", hint: "Cazarrecompensas Star Wars serie" },
      { word: "Grogu (Baby Yoda)", hint: "Bebé verde Star Wars serie" },
      { word: "Wednesday Addams", hint: "Gótica familia Addams" },
      { word: "Ted Lasso", hint: "Entrenador optimista fútbol serie" },
      { word: "Tommy Shelby", hint: "Jefe mafioso Peaky Blinders" },
      { word: "Seokgi de El Juego del Calamar", hint: "Protagonista serie coreana" },
      { word: "Bob Esponja", hint: "Esponja cocinera marina" },
      { word: "Patrick Estrella", hint: "Estrella de mar tonto" },
      { word: "Calamardo Tentáculos", hint: "Vecino gruñón Bob Esponja" },
      { word: "El Chavo del 8", hint: "Niño barril México clásico" },
      { word: "El Chapulín Colorado", hint: "Superhéroe torpe México" },
      // --- NUEVOS ---
      { word: "Gus Fring", hint: "Dueño Los Pollos Hermanos Breaking Bad" },
      { word: "Tony Soprano", hint: "Jefe mafia italiana HBO" },
      { word: "Don Draper", hint: "Publicista elegante Mad Men" },
      { word: "Alf", hint: "Extraterrestre come gatos" },
      { word: "El Zorro", hint: "Don Diego de la Vega enmascarado" },
      { word: "Spock", hint: "Vulcano orejas puntiagudas Star Trek" },
      { word: "Don Ramón", hint: "Debe 14 meses de renta Chavo" },
      { word: "Quico", hint: "Niño cachetón llorón Chavo" },
      { word: "La Chilindrina", hint: "Niña pecas llanto Chavo" },
      { word: "Pepe Argento", hint: "Zapatero machista Casados con Hijos" },
      { word: "Moni Argento", hint: "Cafecito Casados con Hijos" },
      { word: "Mario Santos", hint: "Logística y fuego Los Simuladores" },
      { word: "Pablo Lamponne", hint: "Técnica y movilidad Los Simuladores" },
      { word: "Emilio Ravenna", hint: "Actor mil caras Los Simuladores" },
      { word: "Gabriel Medina", hint: "Investigación sensible Los Simuladores" },
      { word: "Doctor Who", hint: "Viajero del tiempo cabina azul" }
    ]
  },

  "Históricos y Mitológicos": {
    icon: "⚔️",
    color: "#ef4444",
    words: [
      { word: "Alejandro Magno", hint: "Conquistador griego historia antigua" },
      { word: "Julio César", hint: "Emperador romano asesinado" },
      { word: "Cleopatra", hint: "Reina del antiguo Egipto" },
      { word: "Napoleón Bonaparte", hint: "Emperador francés historia" },
      { word: "Adolf Hitler", hint: "Dictador nazi Segunda Guerra" },
      { word: "Winston Churchill", hint: "Primer ministro inglés guerra" },
      { word: "Abraham Lincoln", hint: "Presidente abolió esclavitud EEUU" },
      { word: "George Washington", hint: "Primer presidente Estados Unidos" },
      { word: "Leonardo da Vinci", hint: "Artista inventor italiano" },
      { word: "Galileo Galilei", hint: "Astrónomo italiano sistema solar" },
      { word: "Isaac Newton", hint: "Física gravedad manzana" },
      { word: "Albert Einstein", hint: "Física relatividad teoría" },
      { word: "Marie Curie", hint: "Científica polaca radioactividad" },
      { word: "Charles Darwin", hint: "Evolución especies naturalista" },
      { word: "Sigmund Freud", hint: "Padre del psicoanálisis" },
      { word: "Karl Marx", hint: "Filósofo comunismo capitalismo" },
      { word: "Nikola Tesla", hint: "Inventor electricidad corriente alterna" },
      { word: "Thomas Edison", hint: "Inventor bombilla eléctrica" },
      { word: "Cristóbal Colón", hint: "Descubrió América 1492" },
      { word: "Marco Polo", hint: "Explorador Venecia China" },
      { word: "Genghis Khan", hint: "Conquistador mongol historia" },
      { word: "Atila el Huno", hint: "Guerrero bárbaro historia" },
      { word: "Vlad el Empalador", hint: "Origen Drácula historia" },
      { word: "Juana de Arco", hint: "Heroína francesa quemada hoguera" },
      { word: "El Rey Arturo", hint: "Rey legendario Camelot" },
      { word: "Robin Hood", hint: "Ladrón que roba ricos" },
      { word: "Guillermo Tell", hint: "Ballestero suizo manzana cabeza" },
      { word: "Zeus", hint: "Dios del rayo Grecia" },
      { word: "Poseidón", hint: "Dios del mar Grecia" },
      { word: "Hades", hint: "Villano Hércules Disney" }, // (Mantenido del original)
      { word: "Atenea", hint: "Diosa sabiduría Grecia" },
      { word: "Apolo", hint: "Dios del sol Grecia" },
      { word: "Artemisa", hint: "Diosa de la caza Grecia" },
      { word: "Ares", hint: "Dios de la guerra Grecia" },
      { word: "Hermes", hint: "Mensajero de los dioses Grecia" },
      { word: "Hera", hint: "Reina de los dioses Grecia" },
      { word: "Afrodita", hint: "Diosa del amor Grecia" },
      { word: "Hércules", hint: "Semidiós película Disney" },
      { word: "Aquiles", hint: "Guerrero talón Grecia Troya" },
      { word: "Odiseo", hint: "Protagonista La Odisea Grecia" },
      { word: "Paris de Troya", hint: "Príncipe causó guerra Troya" },
      { word: "Perseo", hint: "Mató a Medusa Grecia" },
      { word: "Teseo", hint: "Mató al Minotauro Grecia" },
      { word: "Medusa", hint: "Serpientes en cabeza mitología" },
      { word: "El Minotauro", hint: "Mitad toro mitad hombre Grecia" },
      { word: "Ra", hint: "Dios sol antiguo Egipto" },
      { word: "Osiris", hint: "Dios muerte antiguo Egipto" },
      { word: "Isis", hint: "Diosa madre antiguo Egipto" },
      { word: "Anubis", hint: "Dios chacal muerte Egipto" },
      { word: "Horus", hint: "Dios cielo halcón Egipto" },
      { word: "Thor (mitología)", hint: "Dios trueno nórdico" },
      { word: "Odín", hint: "Dios supremo nórdico" },
      { word: "Loki (mitología)", hint: "Dios engaño nórdico" },
      { word: "Freya", hint: "Diosa amor nórdica" },
      { word: "Jesús de Nazaret", hint: "Figura central cristianismo" },
      { word: "Moisés", hint: "Profeta separa aguas Biblia" },
      { word: "San Martín", hint: "Libertador Padre Patria Argentina" },
      { word: "Belgrano", hint: "Creador bandera argentina" },
      // --- NUEVOS ---
      { word: "Nelson Mandela", hint: "Líder sudafricano anti-apartheid" },
      { word: "Martin Luther King", hint: "Líder derechos civiles I have a dream" },
      { word: "Mahatma Gandhi", hint: "Líder pacifista India" },
      { word: "Madre Teresa de Calcuta", hint: "Monja misionera santa" },
      { word: "Ana Frank", hint: "Niña judía diario Holocausto" },
      { word: "William Shakespeare", hint: "Escritor Romeo y Julieta" },
      { word: "Domingo Faustino Sarmiento", hint: "Prócer maestro argentino" },
      { word: "Martín Miguel de Güemes", hint: "Prócer gaucho Salta" },
      { word: "Juana Azurduy", hint: "Heroína independencia Sudamérica" },
      { word: "Prometeo", hint: "Robó el fuego a los dioses" },
      { word: "Ícaro", hint: "Voló cerca del sol alas cera" },
      { word: "Pegaso", hint: "Caballo alado mitológico" },
      { word: "Quetzalcóatl", hint: "Serpiente emplumada azteca" }
    ]
  },

};

// Paleta de colores para avatares en lobby
const AVATAR_COLORS = [
  '#f97316', '#a78bfa', '#10b981', '#f59e0b',
  '#06b6d4', '#ec4899', '#3b82f6', '#ef4444',
  '#84cc16', '#8b5cf6'
];