// =============================================
// =========== DATOS DEL JUEGO =================
// =============================================

const CATEGORIES = {
  "Personajes Disney": {
    icon: "🏰",
    color: "#a78bfa",
    words: [
      { word: "Mickey Mouse", hint: "Mascota Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mickey-mouse35.png?raw=true" },
      { word: "Minnie Mouse", hint: "Novia de Mickey", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Minnie_Mouse.webp?raw=true" },
      { word: "Pato Donald", hint: "Pato enojón Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Donald-duck25.webp?raw=true" },
      { word: "Goofy", hint: "Perro torpe Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Goofy_Duckipedia.png?raw=true" },
      { word: "Pluto", hint: "Perro de Mickey", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Pluto_the_pup.webp?raw=true" },
      { word: "Chip y Dale", hint: "Ardillas traviesas Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Chip_y_Dale.webp?raw=true" },
      { word: "El Pato Lucas", hint: "Pato Looney Tunes", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Pato_Lucas_Classic.webp?raw=true" },
      { word: "Bugs Bunny", hint: "Conejo Looney Tunes", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Bugs_Bunny_Looney_Tunes.webp?raw=true" },
      { word: "Tweety", hint: "Canario Looney Tunes", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Tweety.svg.png?raw=true" },
      { word: "Simba", hint: "Película Rey León", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Simba_cachorro.webp?raw=true" },
      { word: "Mufasa", hint: "Película Rey León", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/MufasaTheLionKing02.webp?raw=true" },
      { word: "Nala", hint: "Película Rey León", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Nala_from_The_Lion_King.png?raw=true" },
      { word: "Timón", hint: "Suricata Rey León", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Timon-icon.webp?raw=true" },
      { word: "Pumba", hint: "Jabalí Rey León", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Pumbaa2.webp?raw=true" },
      { word: "Scar", hint: "Villano Rey León", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Clipscarsmirk.webp?raw=true" },
      { word: "Ariel", hint: "Película La Sirenita", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/ariel-disney.webp?raw=true" },
      { word: "Úrsula", hint: "Bruja La Sirenita", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Ursula.webp?raw=true" },
      { word: "Sebastián", hint: "Cangrejo La Sirenita", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/SEBASTIANbio.webp?raw=true" },
      { word: "Flounder", hint: "Pez La Sirenita", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/FlounderBIO.webp?raw=true" },
      { word: "El Príncipe Eric", hint: "Príncipe La Sirenita", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Eric_2021.webp?raw=true" },
      { word: "Blancanieves", hint: "Princesa Disney clásica", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Blancanieves.webp?raw=true" },
      { word: "La Madrastra Malvada", hint: "Villana Blancanieves", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Lady_Tremaine_KHBBS.webp?raw=true" },
      { word: "Cenicienta", hint: "Princesa Disney clásica", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Cenicienta_personaje.webp?raw=true" },
      { word: "El Hada Madrina", hint: "Hada Cenicienta", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/HadamadrinaCNN.webp?raw=true" },
      { word: "La Bella Durmiente", hint: "Princesa Disney clásica", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/bella_durmiente.png?raw=true" },
      { word: "Maléfica", hint: "Bruja Bella Durmiente", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Malefica.webp?raw=true" },
      { word: "Bella", hint: "Película La Bestia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Belle_transparent.webp?raw=true" },
      { word: "La Bestia", hint: "Película Bella y Bestia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Beast_transparent.webp?raw=true" },
      { word: "Gastón", hint: "Villano Bella y Bestia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Gaston_transparent.webp?raw=true" },
      { word: "Lumière", hint: "Candelabro Bella y Bestia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Lumiere_transparente.webp?raw=true" },
      { word: "Ding Dong", hint: "Reloj Bella y Bestia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/dingdong2.webp?raw=true" },
      { word: "Aladdín", hint: "Película Disney Aladdín", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Aladdin_29.webp?raw=true" },
      { word: "Jasmine", hint: "Princesa de Agrabah", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Jasmine_(Aladdin).png?raw=true" },
      { word: "Jafar", hint: "Villano de Agrabah", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Jafar_001.webp?raw=true" },
      { word: "El Genio", hint: "Genio de la lámpara", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Genie5.webp?raw=true" },
      { word: "Iago", hint: "Loro de Jafar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Iago_KHREC.webp?raw=true" },
      { word: "Woody", hint: "Vaquero Toy Story", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Woody_29.webp?raw=true" },
      { word: "Buzz Lightyear", hint: "Astronauta Toy Story", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Buzz_Lightyear_29.webp?raw=true" },
      { word: "Jessie", hint: "Vaquera Toy Story", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Jessie_TS.webp?raw=true" },
      { word: "Rex", hint: "Dinosaurio Toy Story", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/-Rex-.webp?raw=true" },
      { word: "Hamm", hint: "Chanchito Toy Story", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Hamm_KHIII.png?raw=true" },
      { word: "El Señor Cara de Papa", hint: "Juguete Toy Story", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mr._Potato_Head_29.webp?raw=true" },
      { word: "Elsa", hint: "Película Frozen", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Elsa.webp?raw=true" },
      { word: "Anna", hint: "Película Frozen", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Anna_Render.webp?raw=true" },
      { word: "Olaf", hint: "Muñeco nieve Frozen", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Olaf_transparent.webp?raw=true" },
      { word: "Kristoff", hint: "Joven Frozen", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Kristoff_1.webp?raw=true" },
      { word: "Hans", hint: "Príncipe Frozen", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/WIKI_HANS-0.webp?raw=true" },
      { word: "Nemo", hint: "Pez payaso Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Nemo-FN.webp?raw=true" },
      { word: "Dory", hint: "Pez azul Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Dory-FN.webp?raw=true" },
      { word: "Marlin", hint: "Papá de Nemo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Marlin_BaD_render.webp?raw=true" },
      { word: "El Tiburón Bruce", hint: "Tiburón Buscando a Nemo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/bruce_tiburon.png?raw=true" },
      { word: "Remy", hint: "Rata cocinera Ratatouille", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/RemyTheRat.webp?raw=true" },
      { word: "WALL-E", hint: "Robot basura Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Wall-e.webp?raw=true" },
      { word: "Rayo McQueen", hint: "Auto de carreras Cars", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Rayo_McQueen.webp?raw=true" },
      { word: "Mate", hint: "Grúa rústica Cars", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mate_CAelC_render.webp?raw=true" },
      { word: "Edna Moda", hint: "Diseñadora Los Increíbles", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/I2_-_Edna.webp?raw=true" },
      { word: "Mr. Increíble", hint: "Superhéroe Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mr._Increible.webp?raw=true" },
      { word: "Mirabel", hint: "Película Encanto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mirabel_Madrigal_2.webp?raw=true" },
      { word: "Elastigirl", hint: "Superheroína Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Helen_Parr.png?raw=true" },
      { word: "Dash", hint: "Superhéroe Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/dash.png?raw=true" },
      { word: "Bruno", hint: "Película Encanto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Bruno_Madrigal.webp?raw=true" },
      { word: "Hércules", hint: "Semidiós película Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Hercules-imgchrt.webp?raw=true" },
      { word: "Megara", hint: "Heroína Hércules Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Megara_transparent.webp?raw=true" },
      { word: "Hades", hint: "Villano Hércules Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Hades_de_Disney_.webp?raw=true" },
      { word: "Mulan", hint: "Guerrera película Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mulan-Disney.webp?raw=true" },
      { word: "Moana", hint: "Princesa oceánica Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Moana_Moana2_render.webp?raw=true" },
      { word: "Maui", hint: "Semidiós película Moana", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Maui.webp?raw=true" },
      { word: "Tiana", hint: "Princesa Sapo Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Tiana_Disney.png?raw=true" },
      { word: "Pocahontas", hint: "Princesa nativa Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Pocahontas_Disney.webp?raw=true" },
      { word: "Stitch", hint: "Alien azul Lilo y Stitch", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Stitch_(Lilo_&_Stitch).svg.png?raw=true" },
      { word: "Lilo", hint: "Niña hawaiana Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Lilo.webp?raw=true" },
      { word: "Bambi", hint: "Ciervo clásico Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Bambi.webp?raw=true" },
      { word: "Dumbo", hint: "Elefante orejón Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Dumbo-HQ.webp?raw=true" },
      { word: "Pinocho", hint: "Marioneta clásico Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Pinocho.webp?raw=true" },
      { word: "Pepe Grillo", hint: "Grillo Pinocho Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Pepe_Grillo.webp?raw=true" },
      { word: "Mowgli", hint: "Niño El Libro de la Selva", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mowgli-Disney.webp?raw=true" },
      { word: "Baloo", hint: "Oso El Libro de la Selva", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Baloo.webp?raw=true" },
      { word: "Shere Khan", hint: "Tigre El Libro de la Selva", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/ShereKhan.webp?raw=true" },
      { word: "Jack Skellington", hint: "Rey del Espanto Halloween", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Jack_Skellington.png?raw=true" },
      { word: "Capitán Garfio", hint: "Villano Peter Pan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Captain_Garfio.webp?raw=true" },
      { word: "Campanita", hint: "Hada Peter Pan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/campanita.png?raw=true" },
      { word: "Mérida", hint: "Princesa Valiente Pixar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Merida.webp?raw=true" },
      { word: "Rapunzel", hint: "Princesa pelos largos Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Rapunzel.webp?raw=true" },
      { word: "Tarzán", hint: "Hombre mono Disney", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Tarzan.webp?raw=true" },
      { word: "Jane Porter", hint: "Exploradora enamorada de Tarzán", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Jane.webp?raw=true" },
      { word: "Mushu", hint: "Dragón rojo Mulán", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mushu.webp?raw=true" },
      { word: "Cruella de Vil", hint: "Villana 101 Dálmatas", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Cruella_De_Vil.png?raw=true" },
      { word: "Mary Poppins", hint: "Niñera mágica con paraguas", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/mary_poppins.png?raw=true" },
      { word: "Alicia", hint: "Niña País de las Maravillas", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Alicia_Disney.webp?raw=true" },
      { word: "Sombrerero Loco", hint: "Amigo de Alicia toma té", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Sombrerero_Loco.webp?raw=true" },
      { word: "Alegría", hint: "Emoción amarilla Intensamente", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/alegria.webp?raw=true" },
      { word: "Tristeza", hint: "Emoción azul Intensamente", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/tristeza.webp?raw=true" },
      { word: "Furia", hint: "Emoción roja Intensamente", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/furia.webp?raw=true" },
      { word: "Miguel", hint: "Niño músico Coco", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Miguel.webp?raw=true" },
      { word: "Héctor", hint: "Esqueleto amigo Coco", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/hector_coco.webp?raw=true" },
      { word: "Baymax", hint: "Robot médico inflable Grandes Héroes", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Baymax.webp?raw=true" },
      { word: "Ralph el Demoledor", hint: "Villano arcade que quiere ser bueno", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Ralph.webp?raw=true" },
      { word: "Vanellope", hint: "Niña corredora Sugar Rush", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Vanellope.webp?raw=true" },
      { word: "Mike Wazowski", hint: "Monstruo verde un ojo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Mike.webp?raw=true" },
      { word: "James P. Sullivan", hint: "Monstruo peludo azul y violeta", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/James_P_Sullivan.webp?raw=true" },
      { word: "Boo", hint: "Niña humana Monsters Inc", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/Boo.webp?raw=true" }
    ]
  },

  "Superhéroes": {
    icon: "🦸",
    color: "#f59e0b",
    words: [
      { word: "Spider-Man", hint: "Hombre Araña Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/spiderman.webp?raw=true" },
      { word: "Iron Man", hint: "Tony Stark Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Iron-Man.webp?raw=true" },
      { word: "Capitán América", hint: "Escudo Marvel Avengers", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Captain-America.webp?raw=true" },
      { word: "Thor", hint: "Dios del Trueno Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Thor.webp?raw=true" },
      { word: "Hulk", hint: "Gigante verde Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Hulk.png?raw=true" },
      { word: "Viuda Negra", hint: "Espía Avengers Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Black_Widow.webp?raw=true" },
      { word: "Ojo de Halcón", hint: "Arquero Avengers Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/ojodehalcon.png?raw=true" },
      { word: "Ant-Man", hint: "Superhéroe pequeño Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Ant-Man.webp?raw=true" },
      { word: "Doctor Strange", hint: "Hechicero Supremo Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/drStrange.png?raw=true" },
      { word: "Pantera Negra", hint: "Rey de Wakanda", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/pantera_negra.png?raw=true" },
      { word: "Bruja Escarlata", hint: "Poderes de caos Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/breujaEscarlata.webp?raw=true" },
      { word: "Visión", hint: "Androide Avengers Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/vision.webp?raw=true" },
      { word: "Falcon", hint: "Alas metálicas Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/falcon.png?raw=true" },
      { word: "Deadpool", hint: "Mercenario cómico Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Deadpool.webp?raw=true" },
      { word: "Wolverine", hint: "Garras adamantio X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Wolverine.webp?raw=true" },
      { word: "Star-Lord", hint: "Líder Guardianes Galaxia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Star-Lord.png?raw=true" },
      { word: "Gamora", hint: "Guerrera Guardianes Galaxia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Gamora.webp?raw=true" },
      { word: "Drax", hint: "Destructor Guardianes Galaxia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Drax.webp?raw=true" },
      { word: "Groot", hint: "Árbol Guardianes Galaxia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/groot.webp?raw=true" },
      { word: "Rocket Raccoon", hint: "Mapache Guardianes Galaxia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Rocket.webp?raw=true" },
      { word: "Thanos", hint: "Villano Guante del Infinito", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Thanos_.webp?raw=true" },
      { word: "Loki", hint: "Dios del engaño Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Loki.webp?raw=true" },
      { word: "Cíclope", hint: "Rayos ojos X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Cyclope.webp?raw=true" },
      { word: "Tormenta", hint: "Controla el clima X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/tormenta.webp?raw=true" },
      { word: "Bestia", hint: "Hombre azul X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Bestia.webp?raw=true" },
      { word: "Magneto", hint: "Controla el metal X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/magneto.webp?raw=true" },
      { word: "Profesor X", hint: "Líder de los X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/profesorX.png?raw=true" },
      { word: "Mística", hint: "Metamorfa X-Men", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Mistica.webp?raw=true" },
      { word: "Venom", hint: "Simbionte negro Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Venom.webp?raw=true" },
      { word: "El Duende Verde", hint: "Villano Spider-Man", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/duendeVerde.webp?raw=true" },
      { word: "Doctor Octopus", hint: "Tentáculos Spider-Man", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Doc_Octopus.webp?raw=true" },
      { word: "Electro", hint: "Villano eléctrico Spider-Man", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Electro_Max.webp?raw=true" },
      { word: "Ultron", hint: "Robot villano Avengers", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/ultron.png?raw=true" },
      { word: "Superman", hint: "Superhéroe Kryptón DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Superman.png?raw=true" },
      { word: "Batman", hint: "Murciélago Gotham DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Batman.png?raw=true" },
      { word: "Mujer Maravilla", hint: "Guerrera amazona DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/mujerMaravilla.png?raw=true" },
      { word: "Flash", hint: "Superhéroe más rápido DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/The_Flash.png?raw=true" },
      { word: "Linterna Verde", hint: "Anillo poder DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/linternaVerde.webp?raw=true" },
      { word: "Aquaman", hint: "Rey de Atlantis DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/aquaman.png?raw=true" },
      { word: "Shazam", hint: "Niño superhéroe DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Shazam.png?raw=true" },
      { word: "Cyborg", hint: "Mitad hombre mitad máquina DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/cyborgs.png?raw=true" },
      { word: "Supergirl", hint: "Prima de Superman DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Supergirl.webp?raw=true" },
      { word: "El Joker", hint: "Payaso villano Batman", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Joker.png?raw=true" },
      { word: "Harley Quinn", hint: "Novia del Joker DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Harley_Quinn0.webp?raw=true" },
      { word: "El Pingüino", hint: "Villano Batman DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/The_Penguin.webp?raw=true" },
      { word: "Catwoman", hint: "Ladrona Batman DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/catwoman.webp?raw=true" },
      { word: "Bane", hint: "Villano rompe Batman", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Bane.webp?raw=true" },
      { word: "El Acertijo", hint: "Villano acertijos Batman", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Acertijo.png?raw=true" },
      { word: "Robin", hint: "Compañero de Batman", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Robin.png?raw=true" },
      { word: "Raven", hint: "Hechicera Teen Titans", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Raven.webp?raw=true" },
      { word: "Starfire", hint: "Alienígena Teen Titans", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Starfire.png?raw=true" },
      { word: "Kang el Conquistador", hint: "Villano del tiempo Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Kang.png?raw=true" },
      { word: "Silver Surfer", hint: "Heraldo de Galactus Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/silverSurfer.webp?raw=true" },
      { word: "Galactus", hint: "Devorador de planetas Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Galactus.webp?raw=true" },
      { word: "Hulka", hint: "Prima verde de Hulk", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Hulka.webp?raw=true" },
      { word: "Thor Jane Foster", hint: "Jane Foster con martillo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/janeFosterThor.png?raw=true" },
      { word: "Capitana Marvel", hint: "Superheroína cósmica Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/capitanaMarvel.png?raw=true" },
      { word: "Nick Fury", hint: "Director de SHIELD Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Nick_Fury.webp?raw=true" },
      { word: "Spider-Man Miles Morales", hint: "Spider-Man afrolatino Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/miles_morales_01.webp?raw=true" },
      { word: "Daredevil", hint: "Diablo de Hell's Kitchen ciego Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Daredevil.png?raw=true" },
      { word: "Punisher", hint: "El Castigador calavera Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Punisher.webp?raw=true" },
      { word: "Ghost Rider", hint: "Vengador Fantasma moto llamas", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/ghost-rider.png?raw=true" },
      { word: "Mr. Fantástico", hint: "Líder elástico 4 Fantásticos", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Mister_Fantastic.png?raw=true" },
      { word: "La Antorcha Humana", hint: "Fuego 4 Fantásticos", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/antorchaHumana.png?raw=true" },
      { word: "La Mole", hint: "Gigante de piedra 4 Fantásticos", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/laMole.webp?raw=true" },
      { word: "La Mujer Invisible", hint: "Campos de fuerza 4 Fantásticos", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/mujerInvisible.png?raw=true" },
      { word: "Homelander", hint: "Villano Superman The Boys", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Homelander.webp?raw=true" },
      { word: "Omni-Man", hint: "Padre bigotudo Invencible", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Omni-Man.webp?raw=true" },
      { word: "Batgirl", hint: "Chica murciélago DC", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Batgirl.webp?raw=true" },
      { word: "Chapulin Colorado", hint: "Antiheroe mexicano", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/ChapulinColorado.webp?raw=true" },
      { word: "Blade", hint: "Cazador de vampiros Marvel", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/superheroes/Blade.webp?raw=true" }
    ]
  },

  "Animé": {
    icon: "⛩️",
    color: "#f97316",
    words: [
      { word: "Goku", hint: "Protagonista Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Goku.webp?raw=true" },
      { word: "Vegeta", hint: "Príncipe Saiyan Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Vegeta.webp?raw=true" },
      { word: "Piccolo", hint: "Namekiano Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Piccolo.webp?raw=true" },
      { word: "Gohan", hint: "Hijo de Goku Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Gohan.png?raw=true" },
      { word: "Krilin", hint: "Mejor amigo Goku", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Krillin_Trans.webp?raw=true" },
      { word: "Bulma", hint: "Científica Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Bulma.webp?raw=true" },
      { word: "Freezer", hint: "Villano Dragon Ball Z", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Freezer.webp?raw=true" },
      { word: "Cell", hint: "Androide villano Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Cell.webp?raw=true" },
      { word: "Majin Buu", hint: "Villano gordo Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/MajinBuu.webp?raw=true" },
      { word: "Trunks", hint: "Hijo de Vegeta Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/trunks.webp?raw=true" },
      { word: "Androide 18", hint: "Androide Dragon Ball Z", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Android_18.webp?raw=true" },
      { word: "Androide 17", hint: "Androide Dragon Ball Z", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Androide17.webp?raw=true" },
      { word: "Androide 16", hint: "Androide Dragon Ball Z", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Androide_16.webp?raw=true" },
      { word: "Broly", hint: "Saiyan legendario Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/broly.webp?raw=true" },
      { word: "Bardock", hint: "Padre de Goku Dragon Ball", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Bardock_render.webp?raw=true" },
      { word: "Maestro Roshi", hint: "Anciano maestro tortuga", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Muten_Roshi.webp?raw=true" },
      { word: "Goten", hint: "Hijo menor de Goku", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Goten.webp?raw=true" },
      { word: "Mr. Satán", hint: "Campeón de artes marciales", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Mr_Satan.webp?raw=true" },
      { word: "Videl", hint: "Hija de Mr. Satán y esposa de Gohan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Vide.webp?raw=true" },
      { word: "Milk", hint: "Esposa de Goku", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/milk.png?raw=true" },
      { word: "Ten Shin Han", hint: "Guerrero de tres ojos", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Ten_shin_han.webp?raw=true" },
      { word: "Yamcha", hint: "Guerrero cicatriz en la cara", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Yamcha.png?raw=true" },
      { word: "Shenlong", hint: "Dragón de las esferas", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Shen_Lon.webp?raw=true" },
      { word: "Raditz", hint: "Hermano mayor de Goku", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Raditz.webp?raw=true" },
      { word: "Nappa", hint: "Saiyajin calvo compañero de Vegeta", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Nappa.webp?raw=true" },
      { word: "Kaio-sama", hint: "Dios de la galaxia del norte", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Kaiosamanorte.webp?raw=true" },
      { word: "Naruto", hint: "Ninja con zorro Naruto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Naruto.webp?raw=true" },
      { word: "Sasuke", hint: "Rival de Naruto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Sasuke.webp?raw=true" },
      { word: "Sakura", hint: "Kunoichi del equipo 7", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Sakura.webp?raw=true" },
      { word: "Kakashi", hint: "Sensei del equipo 7", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Kakashi.webp?raw=true" },
      { word: "Itachi", hint: "Hermano de Sasuke Naruto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Itachi.webp?raw=true" },
      { word: "Gaara", hint: "Ninja de la arena Naruto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Gaara.webp?raw=true" },
      { word: "Jiraiya", hint: "Maestro sapo Naruto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Jiraiya.webp?raw=true" },
      { word: "Obito", hint: "Villano enmascarado Naruto", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Obito.webp?raw=true" },
      { word: "Pikachu", hint: "Pokémon Eléctrico", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Pikachu.webp?raw=true" },
      { word: "Charizard", hint: "Dragón de fuego inicial", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Charizard.png?raw=true" },
      { word: "Squirtle", hint: "Tortuga de agua inicial", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Squirtle.webp?raw=true" },
      { word: "Bulbasaur", hint: "Dinosaurio planta inicial", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Bulbasaur.png?raw=true" },
      { word: "Mewtwo", hint: "Pokémon legendario clon", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Mewtwo.png?raw=true" },
      { word: "Mew", hint: "Pokémon legendario rosado", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Mew.png?raw=true" },
      { word: "Snorlax", hint: "Pokémon dormilón gigante", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Snorlax.png?raw=true" },
      { word: "Gengar", hint: "Pokémon fantasma morado", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Gengar.png?raw=true" },
      { word: "Eevee", hint: "Pokémon con múltiples evoluciones", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Eevee.png?raw=true" },
      { word: "Jigglypuff", hint: "Pokémon rosado que canta", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Jigglypuff.png?raw=true" },
      { word: "Meowth", hint: "Gato del Team Rocket", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Meowth.webp?raw=true" },
      { word: "Psyduck", hint: "Pato amarillo con dolor de cabeza", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Psyduck.png?raw=true" },
      { word: "Gyarados", hint: "Pokémon de Mar", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Gyarados.png?raw=true" },
      { word: "Luffy", hint: "Capitán pirata One Piece", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Luffy.webp?raw=true" },
      { word: "Tanjiro Kamado", hint: "Cazador de demonios Kimetsu", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Tanjirou.webp?raw=true" },
      { word: "Nezuko Kamado", hint: "Hermana demonio Kimetsu", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Nezuko_manga.webp?raw=true" },
      { word: "Zenitsu", hint: "Cazador rayo Kimetsu", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Zenitsu.webp?raw=true" },
      { word: "Inosuke", hint: "Máscara jabalí Kimetsu", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Inosuke.webp?raw=true" },
      { word: "Deku", hint: "Héroe protagonista My Hero", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Deku.webp?raw=true" },
      { word: "Bakugo", hint: "Explosiones My Hero Academia", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Bakugo.webp?raw=true" },
      { word: "Todoroki", hint: "Hielo y fuego My Hero", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Todoroki.png?raw=true" },
      { word: "All Might", hint: "Símbolo de la paz My Hero", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/AllMight.webp?raw=true" },
      { word: "Eren Yeager", hint: "Attack on Titan protagonista", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Eren_Jaeger.webp?raw=true" },
      { word: "Mikasa Ackerman", hint: "Guerrera Attack on Titan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Mikasa_Ackerman.webp?raw=true" },
      { word: "Armin Arlert", hint: "Estratega Attack on Titan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Armin_Arlert.webp?raw=true" },
      { word: "Levi Ackerman", hint: "Capitán Attack on Titan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Levi_Ackerman.webp?raw=true" },
      { word: "Light Yagami", hint: "Estudiante cuaderno Death Note", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Light-Yagami.webp?raw=true" },
      { word: "L Lawliet", hint: "Detective excéntrico Death Note", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/LDeathNote.webp?raw=true" },
      { word: "Ryuk", hint: "Shinigami Death Note", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Ryuk.webp?raw=true" },
      { word: "Misa Amane", hint: "Modelo Death Note", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/MIsaAmane.webp?raw=true" },
      { word: "Ash Ketchum", hint: "Entrenador Pokémon", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Ash_Ketchum.png?raw=true" },
      { word: "Misty", hint: "Entrenadora agua Pokémon", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Misty.webp?raw=true" },
      { word: "Brock", hint: "Entrenador roca Pokémon", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Brock.png?raw=true" },
      { word: "El Team Rocket", hint: "Villanos Pokémon", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Team_Rocket.webp?raw=true" },
      { word: "Sailor Moon", hint: "Guerrera lunar mágica", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Sailor_Moon.webp?raw=true" },
      { word: "Sailor Mars", hint: "Guerrera del fuego Sailor Moon", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Sailor_Mars.webp?raw=true" },
      { word: "Vegetto", hint: "Fusión Goku y Vegeta", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Vegetto.webp?raw=true" },
      { word: "Gogeta", hint: "Fusión danza Goku Vegeta", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Gogeta.webp?raw=true" },
      { word: "Titan Colosal", hint: "Titan de Attack on Titan", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/titanColosal.png?raw=true" },
      { word: "Oliver Atom", hint: "Fútbol Oliver y Benji", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/OliverAtom.png?raw=true" },
      { word: "Doraemon", hint: "Gato robot del futuro", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Doraemon.png?raw=true" },
      { word: "Seiya de Pegaso", hint: "Caballero del Zodiaco", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/SeiyaPegaso.png?raw=true" },
      { word: "Saitama", hint: "Calvo que vence de un golpe", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Saitama.webp?raw=true" },
      { word: "Gojo Satoru", hint: "Hechicero ojos vendados Jujutsu", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/GojoAnime.webp?raw=true" },
      { word: "Yuji Itadori", hint: "Recipiente de Sukuna Jujutsu", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Yuji_Itadori.webp?raw=true" },
      { word: "Denji", hint: "Pibe motosierra Chainsaw Man", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Denji.png?raw=true" },
      { word: "Makima", hint: "Jefa misteriosa Chainsaw Man", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Makima.webp?raw=true" },
      { word: "Ichigo Kurosaki", hint: "Shinigami espada gigante Bleach", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Ichigo_Kurosaki.webp?raw=true" },
      { word: "Jotaro Kujo", hint: "Star Platinum JoJo's", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/JotaroKujo.webp?raw=true" },
      { word: "Dio Brando", hint: "Villano vampiro ZA WARUDO JoJo's", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Dio_Brando.webp?raw=true" },
      { word: "Gon Freecss", hint: "Niño pescador Hunter x Hunter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Gon.webp?raw=true" },
      { word: "Killua Zoldyck", hint: "Asesino rayo Hunter x Hunter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Killua.webp?raw=true" },
      { word: "Shinji Ikari", hint: "Piloto del EVA-01 Evangelion", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Shinji_Ikari.webp?raw=true" },
      { word: "Asuka Langley", hint: "Piloto pelirroja Evangelion", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Asuka.webp?raw=true" },
      { word: "Inuyasha", hint: "Mitad demonio perro espada", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/anime/Inuyasha.webp?raw=true" }
    ]
  },

  "Videojuegos": {
    icon: "🎮",
    color: "#10b981",
    words: [
      { word: "Mario", hint: "Fontanero Nintendo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Mario.png?raw=true" },
      { word: "Luigi", hint: "Hermano verde de Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Luigi.webp?raw=true" },
      { word: "Princesa Peach", hint: "Princesa de Mario Nintendo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Peach.webp?raw=true" },
      { word: "Bowser", hint: "Rey Koopa Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Bowser.webp?raw=true" },
      { word: "Yoshi", hint: "Dinosaurio verde Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Yoshi.webp?raw=true" },
      { word: "Wario", hint: "Rival gordo de Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Wario.webp?raw=true" },
      { word: "Toad", hint: "Hongo amigo Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Toad.png?raw=true" },
      { word: "Donkey Kong", hint: "Gorila Nintendo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Donkey_Kong.webp?raw=true" },
      { word: "Link", hint: "Héroe de Hyrule Zelda", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Link.webp?raw=true" },
      { word: "Zelda", hint: "Princesa de Hyrule Nintendo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Zelda.png?raw=true" },
      { word: "Sonic", hint: "Erizo veloz SEGA", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Sonic.webp?raw=true" },
      { word: "Tails", hint: "Zorro dos colas SEGA", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Tails.webp?raw=true" },
      { word: "Knuckles", hint: "Equidna rojo SEGA", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Knuckles.png?raw=true" },
      { word: "Shadow", hint: "Erizo negro SEGA", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Shadow.webp?raw=true" },
      { word: "Dr. Eggman", hint: "Villano de Sonic SEGA", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/DrEggman.webp?raw=true" },
      { word: "Kratos", hint: "Dios de la guerra PlayStation", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Kratos.webp?raw=true" },
      { word: "Nathan Drake", hint: "Aventurero Uncharted PlayStation", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/nathan_drake.png?raw=true" },
      { word: "Joel", hint: "Sobreviviente The Last of Us", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Joel.png?raw=true" },
      { word: "Ellie", hint: "Joven The Last of Us", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Ellie.webp?raw=true" },
      { word: "Lara Croft", hint: "Arqueóloga Tomb Raider", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/LaraCroft.png?raw=true" },
      { word: "Crash Bandicoot", hint: "Marsupial loco PlayStation", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Crash_Bandicoot.webp?raw=true" },
      { word: "Cloud Strife", hint: "Espadón Final Fantasy VII", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Cloud_Strife.png?raw=true" },
      { word: "Master Chief", hint: "Spartan Halo Xbox", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Master_chief.png?raw=true" },
      { word: "Geralt de Rivia", hint: "Brujo The Witcher", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Geralt_of_Rivia.webp?raw=true" },
      { word: "Solid Snake", hint: "Espía Metal Gear", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/SolidSnake.png?raw=true" },
      { word: "Ezio Auditore", hint: "Asesino Assassin's Creed", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Ezio_Auditore.webp?raw=true" },
      { word: "Arthur Morgan", hint: "Vaquero Red Dead Redemption", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/ArthurMorgan.webp?raw=true" },
      { word: "John Marston", hint: "Vaquero Red Dead Redemption 2", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Marston.webp?raw=true" },
      { word: "CJ", hint: "Protagonista GTA San Andreas", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Cj.webp?raw=true" },
      { word: "Trevor", hint: "Loco GTA V", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Trevor_Philips.webp?raw=true" },
      { word: "Michael", hint: "Ladrón GTA V", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/michael.png?raw=true" },
      { word: "Franklin", hint: "Ladrón GTA V", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Franklin.webp?raw=true" },
      { word: "Mega Man", hint: "Robot azul Capcom", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Mega_Man.webp?raw=true" },
      { word: "Pac-Man", hint: "Come puntos arcade", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Pac-Man.webp?raw=true" },
      { word: "Scorpion", hint: "Ninja fuego Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Scorpion.png?raw=true" },
      { word: "Sub-Zero", hint: "Ninja hielo Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/subzero.webp?raw=true" },
      { word: "Liu Kang", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/LiuKang.png?raw=true" },
      { word: "Kung Lao", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/KungLao.webp?raw=true" },
      { word: "Raiden", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Raiden.png?raw=true" },
      { word: "Johnny Cage", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/johnny_cage.png?raw=true" },
      { word: "Jax", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/jax.webp?raw=true" },
      { word: "Kitana", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/kitana.webp?raw=true" },
      { word: "Jade", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Jade.webp?raw=true" },
      { word: "Mileena", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Mileena.png?raw=true" },
      { word: "Sonya Blade", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/sonyaBlade.png?raw=true" },
      { word: "Sindel", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/sindel.webp?raw=true" },
      { word: "Kano", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Kano.webp?raw=true" },
      { word: "Cyrax", hint: "Personaje Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Cyrax.webp?raw=true" },
      { word: "Ryu", hint: "Peleador Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Ryu.png?raw=true" },
      { word: "Ken", hint: "Rival de Ryu Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Ken.png?raw=true" },
      { word: "Chun-Li", hint: "Peleadora Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Chun-Li.webp?raw=true" },
      { word: "Guile", hint: "Peleador Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Guile.png?raw=true" },
      { word: "Zangief", hint: "Peleador Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Zangief.png?raw=true" },
      { word: "Blanka", hint: "Peleadora Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Blanka.webp?raw=true" },
      { word: "Steve de Minecraft", hint: "Constructor mundo pixelado", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Steve.webp?raw=true" },
      { word: "Creeper", hint: "Bomba verde Minecraft", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Creeper.webp?raw=true" },
      { word: "Samus Aran", hint: "Cazarrecompensas Metroid Nintendo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Samus_Aran.webp?raw=true" },
      { word: "Kirby", hint: "Bola rosa Nintendo", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Kirby.webp?raw=true" },
      { word: "Bowser Jr.", hint: "Hijo de Bowser Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Bowser_Jr.webp?raw=true" },
      { word: "Waluigi", hint: "Rival de Luigi Mario", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Waluigi.png?raw=true" },
      { word: "Diddy Kong", hint: "Mono amigo Donkey Kong", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Diddy_Kong.webp?raw=true" },
      { word: "Leon S. Kennedy", hint: "Policía rubio Resident Evil", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Leon_Kennedy.webp?raw=true" },
      { word: "Chris Redfield", hint: "Personaje Resident Evil", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Chris_Redfield.webp?raw=true" },
      { word: "Ashley Graham", hint: "Personaje Resident Evil", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Ashleyl.webp?raw=true" },
      { word: "Ada Wong", hint: "Personaje Resident Evil", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Ada_Wong.webp?raw=true" },
      { word: "Ramón Salazar", hint: "Villano Resident Evil", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/ramonSalazar.png?raw=true" },
      { word: "Gordon Freeman", hint: "Científico palanca Half-Life", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Gordon_Freeman.webp?raw=true" },
      { word: "Doomguy", hint: "Mata demonios Doom", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Doomguy.png?raw=true" },
      { word: "Shao Kahn", hint: "Emperador villano principal de Mortal Kombat", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/shao-kahn.webp?raw=true" },
      { word: "Rayman", hint: "Héroe sin extremidades de Ubisoft", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Rayman.webp?raw=true" },
      { word: "Freddy", hint: "Oso animatrónico de terror FNAF", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Freddy.webp?raw=true" },
      { word: "Golden Freddy", hint: "Oso animatrónico de terror FNAF", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Golden_Freddy.webp?raw=true" },
      { word: "Chica", hint: "Pollo animatrónico de terror FNAF", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Chica.webp?raw=true" },
      { word: "Foxy", hint: "Zorro animatrónico de terror FNAF", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Foxy.webp?raw=true" },
      { word: "Bonnie", hint: "Conejo animatrónico de terror FNAF", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/Bonnie.webp?raw=true" },
      { word: "M. Bison", hint: "Villano dictador Street Fighter", image: "https://github.com/LucasN01/Juego_Quien_Soy/blob/main/image/personajes/videojuegos/M._Bison.webp?raw=true" }
    ]
  },

  "Famosos Mundiales": {
    icon: "🌍",
    color: "#06b6d4",
    words: [
      { word: "Lionel Messi", hint: "10 argentino fútbol mundial", image: "LINK_IMAGEN" },
      { word: "Cristiano Ronaldo", hint: "CR7 fútbol Portugal", image: "LINK_IMAGEN" },
      { word: "Neymar", hint: "Delantero brasileño fútbol", image: "LINK_IMAGEN" },
      { word: "Kylian Mbappé", hint: "Delantero Francia fútbol", image: "LINK_IMAGEN" },
      { word: "Erling Haaland", hint: "Goleador noruego fútbol", image: "LINK_IMAGEN" },
      { word: "Pelé", hint: "Rey del fútbol Brasil", image: "LINK_IMAGEN" },
      { word: "Ronaldinho", hint: "Brasileño genial fútbol", image: "LINK_IMAGEN" },
      { word: "Zinedine Zidane", hint: "Francés volante fútbol", image: "LINK_IMAGEN" },
      { word: "David Beckham", hint: "Inglés modelo fútbol", image: "LINK_IMAGEN" },
      { word: "Michael Jordan", hint: "Leyenda del básquet NBA", image: "LINK_IMAGEN" },
      { word: "LeBron James", hint: "Rey del básquet NBA", image: "LINK_IMAGEN" },
      { word: "Kobe Bryant", hint: "Mamba Negra NBA", image: "LINK_IMAGEN" },
      { word: "Stephen Curry", hint: "Tirador tres puntos NBA", image: "LINK_IMAGEN" },
      { word: "Shaquille O'Neal", hint: "Gigante gracioso NBA", image: "LINK_IMAGEN" },
      { word: "Roger Federer", hint: "Leyenda del tenis suizo", image: "LINK_IMAGEN" },
      { word: "Rafael Nadal", hint: "Rey del polvo de ladrillo tenis", image: "LINK_IMAGEN" },
      { word: "Novak Djokovic", hint: "Número uno tenis serbio", image: "LINK_IMAGEN" },
      { word: "Serena Williams", hint: "Reina del tenis estadounidense", image: "LINK_IMAGEN" },
      { word: "Usain Bolt", hint: "Hombre más rápido atletismo", image: "LINK_IMAGEN" },
      { word: "Michael Phelps", hint: "Rey de la natación olímpica", image: "LINK_IMAGEN" },
      { word: "Muhammad Ali", hint: "Leyenda del boxeo mundial", image: "LINK_IMAGEN" },
      { word: "Mike Tyson", hint: "Boxeador feroz oreja", image: "LINK_IMAGEN" },
      { word: "Floyd Mayweather", hint: "Boxeador invicto rico", image: "LINK_IMAGEN" },
      { word: "Taylor Swift", hint: "Cantante pop estadounidense", image: "LINK_IMAGEN" },
      { word: "Beyoncé", hint: "Reina del pop R&B", image: "LINK_IMAGEN" },
      { word: "Rihanna", hint: "Cantante barbadense pop", image: "LINK_IMAGEN" },
      { word: "Lady Gaga", hint: "Cantante excéntrica pop", image: "LINK_IMAGEN" },
      { word: "Adele", hint: "Cantante baladas británica", image: "LINK_IMAGEN" },
      { word: "Bad Bunny", hint: "Rey del reggaetón", image: "LINK_IMAGEN" },
      { word: "Drake", hint: "Rapero canadiense hip-hop", image: "LINK_IMAGEN" },
      { word: "Eminem", hint: "Rapero blanco Detroit", image: "LINK_IMAGEN" },
      { word: "Michael Jackson", hint: "Rey del pop mundial", image: "LINK_IMAGEN" },
      { word: "Madonna", hint: "Reina del pop", image: "LINK_IMAGEN" },
      { word: "Elvis Presley", hint: "Rey del rock and roll", image: "LINK_IMAGEN" },
      { word: "Freddie Mercury", hint: "Vocalista Queen rock", image: "LINK_IMAGEN" },
      { word: "The Beatles", hint: "Banda legendaria Liverpool", image: "LINK_IMAGEN" },
      { word: "David Bowie", hint: "Rockero excéntrico británico", image: "LINK_IMAGEN" },
      { word: "Shakira", hint: "Cantante colombiana pop", image: "LINK_IMAGEN" },
      { word: "Jennifer Lopez", hint: "JLo cantante actriz", image: "LINK_IMAGEN" },
      { word: "Justin Bieber", hint: "Cantante canadiense pop joven", image: "LINK_IMAGEN" },
      { word: "Ariana Grande", hint: "Cantante pop estadounidense", image: "LINK_IMAGEN" },
      { word: "Leonardo DiCaprio", hint: "Actor Hollywood oscarizado", image: "LINK_IMAGEN" },
      { word: "Brad Pitt", hint: "Actor famoso Hollywood", image: "LINK_IMAGEN" },
      { word: "Tom Cruise", hint: "Actor acción Hollywood", image: "LINK_IMAGEN" },
      { word: "Johnny Depp", hint: "Actor excéntrico Hollywood", image: "LINK_IMAGEN" },
      { word: "Meryl Streep", hint: "Actriz mejor actriz Hollywood", image: "LINK_IMAGEN" },
      { word: "Angelina Jolie", hint: "Actriz humanitaria Hollywood", image: "LINK_IMAGEN" },
      { word: "Scarlett Johansson", hint: "Actriz Viuda Negra Marvel", image: "LINK_IMAGEN" },
      { word: "Keanu Reeves", hint: "Actor Matrix John Wick", image: "LINK_IMAGEN" },
      { word: "Ryan Gosling", hint: "Actor canadiense Hollywood", image: "LINK_IMAGEN" },
      { word: "Elon Musk", hint: "Dueño Tesla SpaceX", image: "LINK_IMAGEN" },
      { word: "Bill Gates", hint: "Fundador Microsoft", image: "LINK_IMAGEN" },
      { word: "Mark Zuckerberg", hint: "Fundador Facebook Meta", image: "LINK_IMAGEN" },
      { word: "Steve Jobs", hint: "Fundador Apple", image: "LINK_IMAGEN" },
      { word: "Barack Obama", hint: "Expresidente Estados Unidos", image: "LINK_IMAGEN" },
      { word: "Donald Trump", hint: "Expresidente Estados Unidos", image: "LINK_IMAGEN" },
      { word: "Selena Gomez", hint: "Cantante actriz Disney", image: "LINK_IMAGEN" },
      { word: "Oprah Winfrey", hint: "Conductora televisiva famosa", image: "LINK_IMAGEN" },
      { word: "Tom Hanks", hint: "Actor Forrest Gump", image: "LINK_IMAGEN" },
      { word: "Robert De Niro", hint: "Actor mafioso leyenda", image: "LINK_IMAGEN" },
      { word: "Morgan Freeman", hint: "Actor voz de Dios", image: "LINK_IMAGEN" },
      { word: "Zendaya", hint: "Actriz Rue Euphoria", image: "LINK_IMAGEN" },
      { word: "Tom Holland", hint: "Actor actual Spider-Man", image: "LINK_IMAGEN" },
      { word: "Dua Lipa", hint: "Cantante pop británica levitating", image: "LINK_IMAGEN" },
      { word: "Rosalía", hint: "Cantante Motomami España", image: "LINK_IMAGEN" },
      { word: "The Weeknd", hint: "Cantante Blinding Lights", image: "LINK_IMAGEN" },
      { word: "Billie Eilish", hint: "Cantante pop pelo verde/rubio", image: "LINK_IMAGEN" },
      { word: "Harry Styles", hint: "Ex One Direction solista", image: "LINK_IMAGEN" },
      { word: "Paul McCartney", hint: "Beatle bajista zurdo", image: "LINK_IMAGEN" },
      { word: "Kurt Cobain", hint: "Líder Nirvana grunge", image: "LINK_IMAGEN" },
      { word: "Pep Guardiola", hint: "DT pelado multicampeón City", image: "LINK_IMAGEN" },
      { word: "Carlo Ancelotti", hint: "DT ceja levantada Madrid", image: "LINK_IMAGEN" },
      { word: "Will Smith", hint: "Actor Príncipe del Rap cachetada", image: "LINK_IMAGEN" }
    ]
  },

  "Famosos Argentinos": {
    icon: "🇦🇷",
    color: "#3b82f6",
    words: [
      { word: "Diego Maradona", hint: "10 ídolo fútbol argentino", image: "LINK_IMAGEN" },
      { word: "Lionel Messi", hint: "10 argentino fútbol mundial", image: "LINK_IMAGEN" },
      { word: "Gabriel Batistuta", hint: "Goleador histórico Argentina", image: "LINK_IMAGEN" },
      { word: "Juan Román Riquelme", hint: "10 Boca fútbol", image: "LINK_IMAGEN" },
      { word: "Carlos Tevez", hint: "Delantero Boca fútbol", image: "LINK_IMAGEN" },
      { word: "Sergio Agüero", hint: "Kun delantero fútbol argentino", image: "LINK_IMAGEN" },
      { word: "Ángel Di María", hint: "Extremo fútbol argentino", image: "LINK_IMAGEN" },
      { word: "Javier Zanetti", hint: "Capitán Inter fútbol", image: "LINK_IMAGEN" },
      { word: "Franco Colapinto", hint: "Piloto F1 argentino", image: "LINK_IMAGEN" },
      { word: "Emanuel Ginóbili", hint: "Básquet NBA San Antonio", image: "LINK_IMAGEN" },
      { word: "Juan Martín del Potro", hint: "Tenista argentino Grande", image: "LINK_IMAGEN" },
      { word: "Charly García", hint: "Rockero leyenda argentina", image: "LINK_IMAGEN" },
      { word: "Gustavo Cerati", hint: "Líder de Soda Stereo", image: "LINK_IMAGEN" },
      { word: "Fito Páez", hint: "Rockero rosarino argentino", image: "LINK_IMAGEN" },
      { word: "Luis Alberto Spinetta", hint: "El Flaco rock argentino", image: "LINK_IMAGEN" },
      { word: "Andrés Calamaro", hint: "Rockero Los Rodríguez Argentina", image: "LINK_IMAGEN" },
      { word: "La Mona Jiménez", hint: "Cuarteto Córdoba Argentina", image: "LINK_IMAGEN" },
      { word: "Rodrigo Bueno", hint: "Cuarteto El Potro Argentina", image: "LINK_IMAGEN" },
      { word: "Los Redondos", hint: "Banda Patricio Rey rock", image: "LINK_IMAGEN" },
      { word: "Lali Espósito", hint: "Cantante actriz argentina", image: "LINK_IMAGEN" },
      { word: "Tini Stoessel", hint: "Cantante argentina pop", image: "LINK_IMAGEN" },
      { word: "Nicki Nicole", hint: "Rapera rosarina argentina", image: "LINK_IMAGEN" },
      { word: "Duki", hint: "Trap argentino popular", image: "LINK_IMAGEN" },
      { word: "Bizarrap", hint: "Productor BZRP sesiones", image: "LINK_IMAGEN" },
      { word: "María Becerra", hint: "Cantante pop argentina", image: "LINK_IMAGEN" },
      { word: "Trueno", hint: "Rapero joven argentino", image: "LINK_IMAGEN" },
      { word: "WOS", hint: "Freestyler cantante argentino", image: "LINK_IMAGEN" },
      { word: "Paulo Londra", hint: "Cantante urbano cordobés", image: "LINK_IMAGEN" },
      { word: "L-Gante", hint: "Cantante cumbia 420", image: "LINK_IMAGEN" },
      { word: "Coscu", hint: "Streamer argentino Twitch", image: "LINK_IMAGEN" },
      { word: "Spreen", hint: "Streamer argentino popular", image: "LINK_IMAGEN" },
      { word: "Luquitas Rodríguez", hint: "Streamer youtuber argentino", image: "LINK_IMAGEN" },
      { word: "Martín Cirio (La Faraona)", hint: "Influencer youtuber argentino", image: "LINK_IMAGEN" },
      { word: "Marcelo Tinelli", hint: "Conductor TV argentino", image: "LINK_IMAGEN" },
      { word: "Susana Giménez", hint: "Diva conductora televisión argentina", image: "LINK_IMAGEN" },
      { word: "Mirtha Legrand", hint: "La Chiqui almuerzos TV", image: "LINK_IMAGEN" },
      { word: "Ricardo Darín", hint: "Actor cine argentino", image: "LINK_IMAGEN" },
      { word: "Guillermo Francella", hint: "Actor cómico argentino", image: "LINK_IMAGEN" },
      { word: "Florencia Peña", hint: "Actriz conductora argentina", image: "LINK_IMAGEN" },
      { word: "Darío Barassi", hint: "Conductor juegos TV argentina", image: "LINK_IMAGEN" },
      { word: "Santiago del Moro", hint: "Conductor Gran Hermano", image: "LINK_IMAGEN" },
      { word: "Guido Kaczka", hint: "Conductor juegos TV argentina", image: "LINK_IMAGEN" },
      { word: "Pampita", hint: "Modelo conductora argentina", image: "LINK_IMAGEN" },
      { word: "Wanda Nara", hint: "Mediática modelo argentina", image: "LINK_IMAGEN" },
      { word: "Javier Milei", hint: "Presidente Argentina actual", image: "LINK_IMAGEN" },
      { word: "Cristina Kirchner", hint: "Expresidenta Argentina", image: "LINK_IMAGEN" },
      { word: "Mauricio Macri", hint: "Expresidente Argentina", image: "LINK_IMAGEN" },
      { word: "Sergio Massa", hint: "Político argentino", image: "LINK_IMAGEN" },
      { word: "Alberto Fernández", hint: "Expresidente Argentina", image: "LINK_IMAGEN" },
      { word: "Patricia Bullrich", hint: "Política ministra argentina", image: "LINK_IMAGEN" },
      { word: "Eva Perón", hint: "Evita primera dama histórica", image: "LINK_IMAGEN" },
      { word: "Juan Domingo Perón", hint: "Expresidente histórico Argentina", image: "LINK_IMAGEN" },
      { word: "José de San Martín", hint: "Libertador Padre Patria Argentina", image: "LINK_IMAGEN" },
      { word: "Manuel Belgrano", hint: "Creador bandera argentina", image: "LINK_IMAGEN" },
      { word: "Emiliano Dibu Martínez", hint: "Arquero Selección mira que te como", image: "LINK_IMAGEN" },
      { word: "Lionel Scaloni", hint: "DT creador de la Scaloneta", image: "LINK_IMAGEN" },
      { word: "Julián Álvarez", hint: "La Araña delantero Selección", image: "LINK_IMAGEN" },
      { word: "Enzo Fernández", hint: "Volante Chelsea campeón del mundo", image: "LINK_IMAGEN" },
      { word: "Carlos Bilardo", hint: "DT Narigón campeón 86", image: "LINK_IMAGEN" },
      { word: "Mercedes Sosa", hint: "La Negra folklore leyenda", image: "LINK_IMAGEN" },
      { word: "Pappo", hint: "El Carpo guitarrista rock", image: "LINK_IMAGEN" },
      { word: "Indio Solari", hint: "Cantante Los Redondos pogo", image: "LINK_IMAGEN" },
      { word: "Emilia Mernes", hint: "Cantante pop brillitos en los ojos", image: "LINK_IMAGEN" },
      { word: "Tiago PZK", hint: "Cantante Gotti Trap/R&B", image: "LINK_IMAGEN" },
      { word: "Migue Granados", hint: "Conductor humorista Olga", image: "LINK_IMAGEN" },
      { word: "Diego Capusotto", hint: "Humorista rock Pomelo/Violencia", image: "LINK_IMAGEN" },
      { word: "Moria Casán", hint: "La One lengua karateca vedette", image: "LINK_IMAGEN" },
      { word: "Adrián Suar", hint: "Productor actor Chueco Polka", image: "LINK_IMAGEN" },
      { word: "Alberto Olmedo", hint: "Capitán Piluso humorista clásico", image: "LINK_IMAGEN" },
      { word: "Jorge Porcel", hint: "Gordo humorista dupla Olmedo", image: "LINK_IMAGEN" }
    ]
  },

  "Personajes de TV": {
    icon: "📺",
    color: "#ec4899",
    words: [
      { word: "Walter White", hint: "Químico Breaking Bad", image: "LINK_IMAGEN" },
      { word: "Jesse Pinkman", hint: "Socio Breaking Bad", image: "LINK_IMAGEN" },
      { word: "Saul Goodman", hint: "Abogado Breaking Bad", image: "LINK_IMAGEN" },
      { word: "Mike Ehrmantraut", hint: "Limpiador Breaking Bad", image: "LINK_IMAGEN" },
      { word: "Jon Snow", hint: "Bastardo Game of Thrones", image: "LINK_IMAGEN" },
      { word: "Daenerys Targaryen", hint: "Madre de dragones GoT", image: "LINK_IMAGEN" },
      { word: "Tyrion Lannister", hint: "Enano inteligente GoT", image: "LINK_IMAGEN" },
      { word: "Cersei Lannister", hint: "Reina villana GoT", image: "LINK_IMAGEN" },
      { word: "Arya Stark", hint: "Asesina lista GoT", image: "LINK_IMAGEN" },
      { word: "Sansa Stark", hint: "Señora de Winterfell GoT", image: "LINK_IMAGEN" },
      { word: "El Rey de la Noche", hint: "Villano zombies GoT", image: "LINK_IMAGEN" },
      { word: "Rick Grimes", hint: "Sheriff Walking Dead", image: "LINK_IMAGEN" },
      { word: "Daryl Dixon", hint: "Ballesta Walking Dead", image: "LINK_IMAGEN" },
      { word: "Negan", hint: "Bate Lucille Walking Dead", image: "LINK_IMAGEN" },
      { word: "Sheldon Cooper", hint: "Genio molesto Big Bang Theory", image: "LINK_IMAGEN" },
      { word: "Leonard Hofstadter", hint: "Físico Big Bang Theory", image: "LINK_IMAGEN" },
      { word: "Penny", hint: "Vecina actriz Big Bang Theory", image: "LINK_IMAGEN" },
      { word: "Howard Wolowitz", hint: "Ingeniero Big Bang Theory", image: "LINK_IMAGEN" },
      { word: "Raj Koothrappali", hint: "Astrofísico Big Bang Theory", image: "LINK_IMAGEN" },
      { word: "Ross Geller", hint: "Paleontólogo Friends", image: "LINK_IMAGEN" },
      { word: "Rachel Green", hint: "Moda café Friends", image: "LINK_IMAGEN" },
      { word: "Monica Geller", hint: "Cocinera perfeccionista Friends", image: "LINK_IMAGEN" },
      { word: "Chandler Bing", hint: "Gracioso sarcástico Friends", image: "LINK_IMAGEN" },
      { word: "Joey Tribbiani", hint: "Actor comedor Friends", image: "LINK_IMAGEN" },
      { word: "Phoebe Buffay", hint: "Cantante rara Friends", image: "LINK_IMAGEN" },
      { word: "Homer Simpson", hint: "Papá torpe Los Simpsons", image: "LINK_IMAGEN" },
      { word: "Marge Simpson", hint: "Mamá pelo azul Simpsons", image: "LINK_IMAGEN" },
      { word: "Bart Simpson", hint: "Niño travieso Los Simpsons", image: "LINK_IMAGEN" },
      { word: "Lisa Simpson", hint: "Niña inteligente Simpsons", image: "LINK_IMAGEN" },
      { word: "Ned Flanders", hint: "Vecino religioso Simpsons", image: "LINK_IMAGEN" },
      { word: "El Señor Burns", hint: "Jefe malvado Simpsons", image: "LINK_IMAGEN" },
      { word: "Cartman", hint: "Gordo malvado South Park", image: "LINK_IMAGEN" },
      { word: "Kenny McCormick", hint: "Muere siempre South Park", image: "LINK_IMAGEN" },
      { word: "Stan Marsh", hint: "Protagonista South Park", image: "LINK_IMAGEN" },
      { word: "Kyle Broflovski", hint: "Judío South Park", image: "LINK_IMAGEN" },
      { word: "Eleven", hint: "Poderes telecinéticos Stranger Things", image: "LINK_IMAGEN" },
      { word: "Mike Wheeler", hint: "Protagonista Stranger Things", image: "LINK_IMAGEN" },
      { word: "Dustin Henderson", hint: "Gracioso Stranger Things", image: "LINK_IMAGEN" },
      { word: "Lucas Sinclair", hint: "Amigo Stranger Things", image: "LINK_IMAGEN" },
      { word: "El Demogorgon", hint: "Monstruo Stranger Things", image: "LINK_IMAGEN" },
      { word: "El Profesor", hint: "Mastermind La Casa de Papel", image: "LINK_IMAGEN" },
      { word: "Berlín", hint: "Antagonista La Casa de Papel", image: "LINK_IMAGEN" },
      { word: "Nairobi", hint: "Jefa talleres La Casa de Papel", image: "LINK_IMAGEN" },
      { word: "Tokio", hint: "Narradora La Casa de Papel", image: "LINK_IMAGEN" },
      { word: "Denver", hint: "Risa La Casa de Papel", image: "LINK_IMAGEN" },
      { word: "Pablo Escobar", hint: "Narcotraficante serie Narcos", image: "LINK_IMAGEN" },
      { word: "Michael Scott", hint: "Jefe ridículo The Office", image: "LINK_IMAGEN" },
      { word: "Dwight Schrute", hint: "Gerente asistente The Office", image: "LINK_IMAGEN" },
      { word: "Jim Halpert", hint: "Bromista The Office", image: "LINK_IMAGEN" },
      { word: "El Mandaloriano", hint: "Cazarrecompensas Star Wars serie", image: "LINK_IMAGEN" },
      { word: "Grogu (Baby Yoda)", hint: "Bebé verde Star Wars serie", image: "LINK_IMAGEN" },
      { word: "Wednesday Addams", hint: "Gótica familia Addams", image: "LINK_IMAGEN" },
      { word: "Ted Lasso", hint: "Entrenador optimista fútbol serie", image: "LINK_IMAGEN" },
      { word: "Tommy Shelby", hint: "Jefe mafioso Peaky Blinders", image: "LINK_IMAGEN" },
      { word: "Seokgi de El Juego del Calamar", hint: "Protagonista serie coreana", image: "LINK_IMAGEN" },
      { word: "Bob Esponja", hint: "Esponja cocinera marina", image: "LINK_IMAGEN" },
      { word: "Patrick Estrella", hint: "Estrella de mar tonto", image: "LINK_IMAGEN" },
      { word: "Calamardo Tentáculos", hint: "Vecino gruñón Bob Esponja", image: "LINK_IMAGEN" },
      { word: "El Chavo del 8", hint: "Niño barril México clásico", image: "LINK_IMAGEN" },
      { word: "El Chapulín Colorado", hint: "Superhéroe torpe México", image: "LINK_IMAGEN" },
      { word: "Gus Fring", hint: "Dueño Los Pollos Hermanos Breaking Bad", image: "LINK_IMAGEN" },
      { word: "Tony Soprano", hint: "Jefe mafia italiana HBO", image: "LINK_IMAGEN" },
      { word: "Don Draper", hint: "Publicista elegante Mad Men", image: "LINK_IMAGEN" },
      { word: "Alf", hint: "Extraterrestre come gatos", image: "LINK_IMAGEN" },
      { word: "El Zorro", hint: "Don Diego de la Vega enmascarado", image: "LINK_IMAGEN" },
      { word: "Spock", hint: "Vulcano orejas puntiagudas Star Trek", image: "LINK_IMAGEN" },
      { word: "Don Ramón", hint: "Debe 14 meses de renta Chavo", image: "LINK_IMAGEN" },
      { word: "Quico", hint: "Niño cachetón llorón Chavo", image: "LINK_IMAGEN" },
      { word: "La Chilindrina", hint: "Niña pecas llanto Chavo", image: "LINK_IMAGEN" },
      { word: "Pepe Argento", hint: "Zapatero machista Casados con Hijos", image: "LINK_IMAGEN" },
      { word: "Moni Argento", hint: "Cafecito Casados con Hijos", image: "LINK_IMAGEN" },
      { word: "Mario Santos", hint: "Logística y fuego Los Simuladores", image: "LINK_IMAGEN" },
      { word: "Pablo Lamponne", hint: "Técnica y movilidad Los Simuladores", image: "LINK_IMAGEN" },
      { word: "Emilio Ravenna", hint: "Actor mil caras Los Simuladores", image: "LINK_IMAGEN" },
      { word: "Gabriel Medina", hint: "Investigación sensible Los Simuladores", image: "LINK_IMAGEN" },
      { word: "Doctor Who", hint: "Viajero del tiempo cabina azul", image: "LINK_IMAGEN" }
    ]
  },

  "Históricos y Mitológicos": {
    icon: "⚔️",
    color: "#ef4444",
    words: [
      { word: "Alejandro Magno", hint: "Conquistador griego historia antigua", image: "LINK_IMAGEN" },
      { word: "Julio César", hint: "Emperador romano asesinado", image: "LINK_IMAGEN" },
      { word: "Cleopatra", hint: "Reina del antiguo Egipto", image: "LINK_IMAGEN" },
      { word: "Napoleón Bonaparte", hint: "Emperador francés historia", image: "LINK_IMAGEN" },
      { word: "Adolf Hitler", hint: "Dictador nazi Segunda Guerra", image: "LINK_IMAGEN" },
      { word: "Winston Churchill", hint: "Primer ministro inglés guerra", image: "LINK_IMAGEN" },
      { word: "Abraham Lincoln", hint: "Presidente abolió esclavitud EEUU", image: "LINK_IMAGEN" },
      { word: "George Washington", hint: "Primer presidente Estados Unidos", image: "LINK_IMAGEN" },
      { word: "Leonardo da Vinci", hint: "Artista inventor italiano", image: "LINK_IMAGEN" },
      { word: "Galileo Galilei", hint: "Astrónomo italiano sistema solar", image: "LINK_IMAGEN" },
      { word: "Isaac Newton", hint: "Física gravedad manzana", image: "LINK_IMAGEN" },
      { word: "Albert Einstein", hint: "Física relatividad teoría", image: "LINK_IMAGEN" },
      { word: "Marie Curie", hint: "Científica polaca radioactividad", image: "LINK_IMAGEN" },
      { word: "Charles Darwin", hint: "Evolución especies naturalista", image: "LINK_IMAGEN" },
      { word: "Sigmund Freud", hint: "Padre del psicoanálisis", image: "LINK_IMAGEN" },
      { word: "Karl Marx", hint: "Filósofo comunismo capitalismo", image: "LINK_IMAGEN" },
      { word: "Nikola Tesla", hint: "Inventor electricidad corriente alterna", image: "LINK_IMAGEN" },
      { word: "Thomas Edison", hint: "Inventor bombilla eléctrica", image: "LINK_IMAGEN" },
      { word: "Cristóbal Colón", hint: "Descubrió América 1492", image: "LINK_IMAGEN" },
      { word: "Marco Polo", hint: "Explorador Venecia China", image: "LINK_IMAGEN" },
      { word: "Genghis Khan", hint: "Conquistador mongol historia", image: "LINK_IMAGEN" },
      { word: "Atila el Huno", hint: "Guerrero bárbaro historia", image: "LINK_IMAGEN" },
      { word: "Vlad el Empalador", hint: "Origen Drácula historia", image: "LINK_IMAGEN" },
      { word: "Juana de Arco", hint: "Heroína francesa quemada hoguera", image: "LINK_IMAGEN" },
      { word: "El Rey Arturo", hint: "Rey legendario Camelot", image: "LINK_IMAGEN" },
      { word: "Robin Hood", hint: "Ladrón que roba ricos", image: "LINK_IMAGEN" },
      { word: "Guillermo Tell", hint: "Ballestero suizo manzana cabeza", image: "LINK_IMAGEN" },
      { word: "Zeus", hint: "Dios del rayo Grecia", image: "LINK_IMAGEN" },
      { word: "Poseidón", hint: "Dios del mar Grecia", image: "LINK_IMAGEN" },
      { word: "Hades", hint: "Villano Hércules Disney", image: "LINK_IMAGEN" },
      { word: "Atenea", hint: "Diosa sabiduría Grecia", image: "LINK_IMAGEN" },
      { word: "Apolo", hint: "Dios del sol Grecia", image: "LINK_IMAGEN" },
      { word: "Artemisa", hint: "Diosa de la caza Grecia", image: "LINK_IMAGEN" },
      { word: "Ares", hint: "Dios de la guerra Grecia", image: "LINK_IMAGEN" },
      { word: "Hermes", hint: "Mensajero de los dioses Grecia", image: "LINK_IMAGEN" },
      { word: "Hera", hint: "Reina de los dioses Grecia", image: "LINK_IMAGEN" },
      { word: "Afrodita", hint: "Diosa del amor Grecia", image: "LINK_IMAGEN" },
      { word: "Hércules", hint: "Semidiós película Disney", image: "LINK_IMAGEN" },
      { word: "Aquiles", hint: "Guerrero talón Grecia Troya", image: "LINK_IMAGEN" },
      { word: "Odiseo", hint: "Protagonista La Odisea Grecia", image: "LINK_IMAGEN" },
      { word: "Paris de Troya", hint: "Príncipe causó guerra Troya", image: "LINK_IMAGEN" },
      { word: "Perseo", hint: "Mató a Medusa Grecia", image: "LINK_IMAGEN" },
      { word: "Teseo", hint: "Mató al Minotauro Grecia", image: "LINK_IMAGEN" },
      { word: "Medusa", hint: "Serpientes en cabeza mitología", image: "LINK_IMAGEN" },
      { word: "El Minotauro", hint: "Mitad toro mitad hombre Grecia", image: "LINK_IMAGEN" },
      { word: "Ra", hint: "Dios sol antiguo Egipto", image: "LINK_IMAGEN" },
      { word: "Osiris", hint: "Dios muerte antiguo Egipto", image: "LINK_IMAGEN" },
      { word: "Isis", hint: "Diosa madre antiguo Egipto", image: "LINK_IMAGEN" },
      { word: "Anubis", hint: "Dios chacal muerte Egipto", image: "LINK_IMAGEN" },
      { word: "Horus", hint: "Dios cielo halcón Egipto", image: "LINK_IMAGEN" },
      { word: "Thor (mitología)", hint: "Dios trueno nórdico", image: "LINK_IMAGEN" },
      { word: "Odín", hint: "Dios supremo nórdico", image: "LINK_IMAGEN" },
      { word: "Loki (mitología)", hint: "Dios engaño nórdico", image: "LINK_IMAGEN" },
      { word: "Freya", hint: "Diosa amor nórdica", image: "LINK_IMAGEN" },
      { word: "Jesús de Nazaret", hint: "Figura central cristianismo", image: "LINK_IMAGEN" },
      { word: "Moisés", hint: "Profeta separa aguas Biblia", image: "LINK_IMAGEN" },
      { word: "San Martín", hint: "Libertador Padre Patria Argentina", image: "LINK_IMAGEN" },
      { word: "Belgrano", hint: "Creador bandera argentina", image: "LINK_IMAGEN" },
      { word: "Nelson Mandela", hint: "Líder sudafricano anti-apartheid", image: "LINK_IMAGEN" },
      { word: "Martin Luther King", hint: "Líder derechos civiles I have a dream", image: "LINK_IMAGEN" },
      { word: "Mahatma Gandhi", hint: "Líder pacifista India", image: "LINK_IMAGEN" },
      { word: "Madre Teresa de Calcuta", hint: "Monja misionera santa", image: "LINK_IMAGEN" },
      { word: "Ana Frank", hint: "Niña judía diario Holocausto", image: "LINK_IMAGEN" },
      { word: "William Shakespeare", hint: "Escritor Romeo y Julieta", image: "LINK_IMAGEN" },
      { word: "Domingo Faustino Sarmiento", hint: "Prócer maestro argentino", image: "LINK_IMAGEN" },
      { word: "Martín Miguel de Güemes", hint: "Prócer gaucho Salta", image: "LINK_IMAGEN" },
      { word: "Juana Azurduy", hint: "Heroína independencia Sudamérica", image: "LINK_IMAGEN" },
      { word: "Prometeo", hint: "Robó el fuego a los dioses", image: "LINK_IMAGEN" },
      { word: "Ícaro", hint: "Voló cerca del sol alas cera", image: "LINK_IMAGEN" },
      { word: "Pegaso", hint: "Caballo alado mitológico", image: "LINK_IMAGEN" },
      { word: "Quetzalcóatl", hint: "Serpiente emplumada azteca", image: "LINK_IMAGEN" }
    ]
  }
};

// Paleta de colores para avatares en lobby
const AVATAR_COLORS = [
  '#f97316', '#a78bfa', '#10b981', '#f59e0b',
  '#06b6d4', '#ec4899', '#3b82f6', '#ef4444',
  '#84cc16', '#8b5cf6'
];